
package GUI;


import pojo.Ban;
import pojo.ChiTietHoaDon;
import pojo.GoiMon;
import pojo.HoaDon;
import pojo.KhachHang;
import pojo.LoaiHang;
import pojo.LoaiKhachHang;
import pojo.NhanVien;
import pojo.SanPham;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

import dao.NhanVienDAO;
import dao.SanPhamDAO;
import dao.BanDAO;
import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.LoaiHangDAO;
import java.math.BigDecimal;
import main.Run;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame implements Runnable{

    int hour, second, minute;
    
    boolean press = false;
    int btnPrevPress = -1;
    ArrayList<Ban> lstBan;
    ArrayList<Ban> ban;
    ArrayList<LoaiHang> lstLoaiHang = new ArrayList<>();;
    ArrayList<SanPham> lstHang = new ArrayList<>();;
    ArrayList<GoiMon> lstMon;
    HoaDon hd_DaThanhToan = new HoaDon();
    
    NhanVien nv;
    KhachHang kh;
    int quyen = Run.tk.getPhanQuyen();
    
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form Menu
     */
    
    public Menu() {
       
        initComponents();
        
        // Đồng hồ
        Thread t =  new Thread(this); 
        t.start();
        
        setDisplay();
        pnQuanLy.hide();
        SoluongMon.setValue(1);
        nv = NhanVienDAO.layNhanVien(Run.tk.getMaNV());
        lbTenNV.setText(nv.getTenNV());
        
        dtm = (DefaultTableModel)tblCacMon.getModel();
        loadDSBan();
        cboLoaiMon.setEnabled(false);
        cboMon.setEnabled(false);
        loadMon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTop = new javax.swing.JPanel();
        lbIconMenu = new javax.swing.JLabel();
        lbIconUser = new javax.swing.JLabel();
        lbTenNV = new javax.swing.JLabel();
        lbIconExit = new javax.swing.JLabel();
        lbTimer = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        pnQuanLy = new javax.swing.JPanel();
        pnQLKho = new javax.swing.JPanel();
        lbIconKho1 = new javax.swing.JLabel();
        lbKho1 = new javax.swing.JLabel();
        pnQLSanPham = new javax.swing.JPanel();
        lbIconCafe = new javax.swing.JLabel();
        lbQLDoUong = new javax.swing.JLabel();
        pnQLHoaDon = new javax.swing.JPanel();
        lbIconDoAn = new javax.swing.JLabel();
        lbQLDoAn = new javax.swing.JLabel();
        pnQLNhanVien = new javax.swing.JPanel();
        lbIconNV = new javax.swing.JLabel();
        lbQLNV = new javax.swing.JLabel();
        pnQLKhachHang = new javax.swing.JPanel();
        lbIconKH = new javax.swing.JLabel();
        lbQLKH = new javax.swing.JLabel();
        pnDoanhThu = new javax.swing.JPanel();
        lbIconBieuDo = new javax.swing.JLabel();
        lbThongKe = new javax.swing.JLabel();
        pnQLDsBan = new javax.swing.JPanel();
        lbIconBieuDo1 = new javax.swing.JLabel();
        lbThongKe1 = new javax.swing.JLabel();
        pnBanhang = new javax.swing.JPanel();
        scpBan = new javax.swing.JScrollPane();
        pnQLBan = new javax.swing.JPanel();
        pnRight = new javax.swing.JPanel();
        pnThemMon = new javax.swing.JPanel();
        cboLoaiMon = new javax.swing.JComboBox<>();
        cboMon = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        SoluongMon = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnDsMonDaGoi = new javax.swing.JPanel();
        scpCacMon = new javax.swing.JScrollPane();
        tblCacMon = new javax.swing.JTable();
        pnThanhToan = new javax.swing.JPanel();
        btnInHD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        lbTitleTongTien = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        lbTitleTienThua = new javax.swing.JLabel();
        lbTienThua = new javax.swing.JLabel();
        pnGhiChu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnChuyenBan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnTimTTKhach = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        lbThongBao = new javax.swing.JLabel();
        btnNhapBill = new javax.swing.JButton();
        btnKHVangLai = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtLoaiKH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDiemTL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnTop.setBackground(new java.awt.Color(235, 151, 100));
        pnTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIconMenu.setBackground(new java.awt.Color(235, 151, 100));
        lbIconMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu.png"))); // NOI18N
        lbIconMenu.setOpaque(true);
        lbIconMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbIconMenuMouseMoved(evt);
            }
        });
        lbIconMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconMenuMousePressed(evt);
            }
        });
        pnTop.add(lbIconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lbIconUser.setBackground(new java.awt.Color(235, 151, 100));
        lbIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_nv.png"))); // NOI18N
        lbIconUser.setOpaque(true);
        lbIconUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbIconUserMouseMoved(evt);
            }
        });
        lbIconUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconUserMouseExited(evt);
            }
        });
        pnTop.add(lbIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 40));

        lbTenNV.setBackground(new java.awt.Color(235, 151, 100));
        lbTenNV.setText("jLabel1");
        lbTenNV.setOpaque(true);
        pnTop.add(lbTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 130, 20));

        lbIconExit.setBackground(new java.awt.Color(235, 151, 100));
        lbIconExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_exit.png"))); // NOI18N
        lbIconExit.setOpaque(true);
        lbIconExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbIconExitMouseMoved(evt);
            }
        });
        lbIconExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbIconExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconExitMouseExited(evt);
            }
        });
        pnTop.add(lbIconExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 40, 40));

        lbTimer.setText("jLabel1");
        pnTop.add(lbTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 4, 130, 30));

        lbDangXuat.setBackground(new java.awt.Color(235, 151, 100));
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_logout.png"))); // NOI18N
        lbDangXuat.setOpaque(true);
        lbDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseMoved(evt);
            }
        });
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseExited(evt);
            }
        });
        pnTop.add(lbDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 40, 40));

        pnQuanLy.setBackground(new java.awt.Color(50, 67, 95));

        pnQLKho.setBackground(new java.awt.Color(50, 67, 95));
        pnQLKho.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLKho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLKhoMouseMoved(evt);
            }
        });
        pnQLKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLKhoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLKhoMouseExited(evt);
            }
        });

        lbIconKho1.setBackground(new java.awt.Color(255, 255, 255));
        lbIconKho1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconKho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_warehouse.png"))); // NOI18N
        lbIconKho1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbKho1.setBackground(new java.awt.Color(255, 255, 255));
        lbKho1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbKho1.setForeground(new java.awt.Color(255, 255, 255));
        lbKho1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKho1.setText("Quản lý kho");
        lbKho1.setMaximumSize(new java.awt.Dimension(114, 15));
        lbKho1.setMinimumSize(new java.awt.Dimension(114, 15));
        lbKho1.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLKhoLayout = new javax.swing.GroupLayout(pnQLKho);
        pnQLKho.setLayout(pnQLKhoLayout);
        pnQLKhoLayout.setHorizontalGroup(
            pnQLKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIconKho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbKho1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLKhoLayout.setVerticalGroup(
            pnQLKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLKhoLayout.createSequentialGroup()
                .addComponent(lbIconKho1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbKho1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pnQLSanPham.setBackground(new java.awt.Color(50, 67, 95));
        pnQLSanPham.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLSanPham.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLSanPhamMouseMoved(evt);
            }
        });
        pnQLSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLSanPhamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLSanPhamMouseExited(evt);
            }
        });

        lbIconCafe.setBackground(new java.awt.Color(255, 255, 255));
        lbIconCafe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_cafe.png"))); // NOI18N
        lbIconCafe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbQLDoUong.setBackground(new java.awt.Color(255, 255, 255));
        lbQLDoUong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbQLDoUong.setForeground(new java.awt.Color(255, 255, 255));
        lbQLDoUong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQLDoUong.setText("Quán lý sản phẩm ");
        lbQLDoUong.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLSanPhamLayout = new javax.swing.GroupLayout(pnQLSanPham);
        pnQLSanPham.setLayout(pnQLSanPhamLayout);
        pnQLSanPhamLayout.setHorizontalGroup(
            pnQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQLDoUong, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(lbIconCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLSanPhamLayout.setVerticalGroup(
            pnQLSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLSanPhamLayout.createSequentialGroup()
                .addComponent(lbIconCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQLDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnQLHoaDon.setBackground(new java.awt.Color(50, 67, 95));
        pnQLHoaDon.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLHoaDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLHoaDonMouseMoved(evt);
            }
        });
        pnQLHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLHoaDonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLHoaDonMouseExited(evt);
            }
        });

        lbIconDoAn.setBackground(new java.awt.Color(255, 255, 255));
        lbIconDoAn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconDoAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_cake.png"))); // NOI18N
        lbIconDoAn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbQLDoAn.setBackground(new java.awt.Color(255, 255, 255));
        lbQLDoAn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbQLDoAn.setForeground(new java.awt.Color(255, 255, 255));
        lbQLDoAn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQLDoAn.setText("Quán lý hóa đơn");
        lbQLDoAn.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLHoaDonLayout = new javax.swing.GroupLayout(pnQLHoaDon);
        pnQLHoaDon.setLayout(pnQLHoaDonLayout);
        pnQLHoaDonLayout.setHorizontalGroup(
            pnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIconDoAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbQLDoAn, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        pnQLHoaDonLayout.setVerticalGroup(
            pnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLHoaDonLayout.createSequentialGroup()
                .addComponent(lbIconDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQLDoAn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnQLNhanVien.setBackground(new java.awt.Color(50, 67, 95));
        pnQLNhanVien.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLNhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLNhanVienMouseMoved(evt);
            }
        });
        pnQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLNhanVienMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLNhanVienMouseExited(evt);
            }
        });

        lbIconNV.setBackground(new java.awt.Color(255, 255, 255));
        lbIconNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_men.png"))); // NOI18N
        lbIconNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbQLNV.setBackground(new java.awt.Color(255, 255, 255));
        lbQLNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbQLNV.setForeground(new java.awt.Color(255, 255, 255));
        lbQLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQLNV.setText("Quản lý nhân viên");
        lbQLNV.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLNhanVienLayout = new javax.swing.GroupLayout(pnQLNhanVien);
        pnQLNhanVien.setLayout(pnQLNhanVienLayout);
        pnQLNhanVienLayout.setHorizontalGroup(
            pnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(lbIconNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLNhanVienLayout.setVerticalGroup(
            pnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLNhanVienLayout.createSequentialGroup()
                .addComponent(lbIconNV, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnQLKhachHang.setBackground(new java.awt.Color(50, 67, 95));
        pnQLKhachHang.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLKhachHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLKhachHangMouseMoved(evt);
            }
        });
        pnQLKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLKhachHangMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLKhachHangMouseExited(evt);
            }
        });

        lbIconKH.setBackground(new java.awt.Color(255, 255, 255));
        lbIconKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_customer.png"))); // NOI18N
        lbIconKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbQLKH.setBackground(new java.awt.Color(255, 255, 255));
        lbQLKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbQLKH.setForeground(new java.awt.Color(255, 255, 255));
        lbQLKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQLKH.setText("Quản lý khách hàng");
        lbQLKH.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLKhachHangLayout = new javax.swing.GroupLayout(pnQLKhachHang);
        pnQLKhachHang.setLayout(pnQLKhachHangLayout);
        pnQLKhachHangLayout.setHorizontalGroup(
            pnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addComponent(lbIconKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnQLKhachHangLayout.setVerticalGroup(
            pnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLKhachHangLayout.createSequentialGroup()
                .addComponent(lbIconKH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnDoanhThu.setBackground(new java.awt.Color(50, 67, 95));
        pnDoanhThu.setPreferredSize(new java.awt.Dimension(115, 115));
        pnDoanhThu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnDoanhThuMouseMoved(evt);
            }
        });
        pnDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnDoanhThuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDoanhThuMouseExited(evt);
            }
        });

        lbIconBieuDo.setBackground(new java.awt.Color(255, 255, 255));
        lbIconBieuDo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconBieuDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_chart.png"))); // NOI18N
        lbIconBieuDo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbThongKe.setBackground(new java.awt.Color(255, 255, 255));
        lbThongKe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongKe.setText("Thống kê doanh thu");
        lbThongKe.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnDoanhThuLayout = new javax.swing.GroupLayout(pnDoanhThu);
        pnDoanhThu.setLayout(pnDoanhThuLayout);
        pnDoanhThuLayout.setHorizontalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIconBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDoanhThuLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDoanhThuLayout.setVerticalGroup(
            pnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoanhThuLayout.createSequentialGroup()
                .addComponent(lbIconBieuDo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnQLDsBan.setBackground(new java.awt.Color(50, 67, 95));
        pnQLDsBan.setPreferredSize(new java.awt.Dimension(115, 115));
        pnQLDsBan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnQLDsBanMouseMoved(evt);
            }
        });
        pnQLDsBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnQLDsBanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnQLDsBanMouseExited(evt);
            }
        });

        lbIconBieuDo1.setBackground(new java.awt.Color(255, 255, 255));
        lbIconBieuDo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconBieuDo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_table.png"))); // NOI18N
        lbIconBieuDo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbThongKe1.setBackground(new java.awt.Color(255, 255, 255));
        lbThongKe1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbThongKe1.setForeground(new java.awt.Color(255, 255, 255));
        lbThongKe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongKe1.setText("Quản lý bàn");
        lbThongKe1.setPreferredSize(new java.awt.Dimension(114, 12));

        javax.swing.GroupLayout pnQLDsBanLayout = new javax.swing.GroupLayout(pnQLDsBan);
        pnQLDsBan.setLayout(pnQLDsBanLayout);
        pnQLDsBanLayout.setHorizontalGroup(
            pnQLDsBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbIconBieuDo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbThongKe1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        pnQLDsBanLayout.setVerticalGroup(
            pnQLDsBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLDsBanLayout.createSequentialGroup()
                .addComponent(lbIconBieuDo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbThongKe1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnQuanLyLayout = new javax.swing.GroupLayout(pnQuanLy);
        pnQuanLy.setLayout(pnQuanLyLayout);
        pnQuanLyLayout.setHorizontalGroup(
            pnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnQLKho, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnQLDsBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnQuanLyLayout.setVerticalGroup(
            pnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuanLyLayout.createSequentialGroup()
                .addGroup(pnQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnQLSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnQLHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnQLNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnQLKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnDoanhThu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnQLKho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(pnQLDsBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBanhang.setPreferredSize(new java.awt.Dimension(839, 568));

        scpBan.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scpBan.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnQLBan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnQLBan.setPreferredSize(new java.awt.Dimension(395, 400));

        javax.swing.GroupLayout pnQLBanLayout = new javax.swing.GroupLayout(pnQLBan);
        pnQLBan.setLayout(pnQLBanLayout);
        pnQLBanLayout.setHorizontalGroup(
            pnQLBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        pnQLBanLayout.setVerticalGroup(
            pnQLBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        scpBan.setViewportView(pnQLBan);

        pnRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRight.setMaximumSize(new java.awt.Dimension(431, 577));
        pnRight.setMinimumSize(new java.awt.Dimension(431, 577));

        pnThemMon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboLoaiMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboLoaiMon.setToolTipText("");
        cboLoaiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiMonActionPerformed(evt);
            }
        });

        cboMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnThem.setBackground(new java.awt.Color(249, 64, 52));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        SoluongMon.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số lượng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Order");

        javax.swing.GroupLayout pnThemMonLayout = new javax.swing.GroupLayout(pnThemMon);
        pnThemMon.setLayout(pnThemMonLayout);
        pnThemMonLayout.setHorizontalGroup(
            pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemMonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMon, 0, 157, Short.MAX_VALUE)
                    .addComponent(cboLoaiMon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addGroup(pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SoluongMon)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnThemMonLayout.setVerticalGroup(
            pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemMonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThemMonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnThemMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cboLoaiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(cboMon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnThemMonLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SoluongMon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        scpCacMon.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scpCacMon.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblCacMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên món", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        scpCacMon.setViewportView(tblCacMon);

        javax.swing.GroupLayout pnDsMonDaGoiLayout = new javax.swing.GroupLayout(pnDsMonDaGoi);
        pnDsMonDaGoi.setLayout(pnDsMonDaGoiLayout);
        pnDsMonDaGoiLayout.setHorizontalGroup(
            pnDsMonDaGoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpCacMon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnDsMonDaGoiLayout.setVerticalGroup(
            pnDsMonDaGoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDsMonDaGoiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scpCacMon, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnInHD.setBackground(new java.awt.Color(72, 210, 156));
        btnInHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInHD.setText("In hóa đơn");
        btnInHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHDActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(72, 210, 156));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setPreferredSize(new java.awt.Dimension(103, 20));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        lbTitleTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTitleTongTien.setText("Tổng tiền");

        lbTongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tiền khách đưa");

        txtTienKhachDua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbTitleTienThua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTitleTienThua.setText("Tiền thừa");

        lbTienThua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnGhiChu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Bàn trống");

        jLabel6.setBackground(new java.awt.Color(128, 128, 255));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(15, 10));

        jLabel7.setText("Đang phục vụ");

        jLabel8.setBackground(new java.awt.Color(102, 255, 102));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(15, 10));

        jLabel9.setText("Bàn đang chọn");

        jLabel10.setBackground(new java.awt.Color(128, 128, 255));
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(15, 10));

        javax.swing.GroupLayout pnGhiChuLayout = new javax.swing.GroupLayout(pnGhiChu);
        pnGhiChu.setLayout(pnGhiChuLayout);
        pnGhiChuLayout.setHorizontalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnGhiChuLayout.setVerticalGroup(
            pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(72, 210, 156));
        jButton1.setText("Tính");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThanhToanLayout = new javax.swing.GroupLayout(pnThanhToan);
        pnThanhToan.setLayout(pnThanhToanLayout);
        pnThanhToanLayout.setHorizontalGroup(
            pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addComponent(lbTitleTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lbTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInHD))
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbTitleTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThanhToanLayout.createSequentialGroup()
                                .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThanhToanLayout.setVerticalGroup(
            pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThanhToanLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTitleTongTien)
                            .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTitleTienThua)
                            .addComponent(lbTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInHD)))
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnChuyenBan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnChuyenBan.setPreferredSize(new java.awt.Dimension(450, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Chuyển bàn");

        javax.swing.GroupLayout pnChuyenBanLayout = new javax.swing.GroupLayout(pnChuyenBan);
        pnChuyenBan.setLayout(pnChuyenBanLayout);
        pnChuyenBanLayout.setHorizontalGroup(
            pnChuyenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChuyenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnChuyenBanLayout.setVerticalGroup(
            pnChuyenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChuyenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addComponent(pnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addComponent(pnThemMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createSequentialGroup()
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnChuyenBan, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                            .addComponent(pnDsMonDaGoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7))))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnThemMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDsMonDaGoi, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnTimTTKhach.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Thông tin khách hàng");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
        });

        jLabel12.setText("Nhập số điện thoại:");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnNhapBill.setBackground(new java.awt.Color(72, 210, 156));
        btnNhapBill.setText("Nhập bill");
        btnNhapBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapBillActionPerformed(evt);
            }
        });

        btnKHVangLai.setBackground(new java.awt.Color(72, 210, 156));
        btnKHVangLai.setText("Khách vãng lai");
        btnKHVangLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHVangLaiActionPerformed(evt);
            }
        });

        jLabel13.setText("Loại khách hàng");

        jLabel14.setText("Tên khách hàng");

        jLabel15.setText("Điểm tích lũy");

        javax.swing.GroupLayout pnTimTTKhachLayout = new javax.swing.GroupLayout(pnTimTTKhach);
        pnTimTTKhach.setLayout(pnTimTTKhachLayout);
        pnTimTTKhachLayout.setHorizontalGroup(
            pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTim))
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addComponent(btnNhapBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKHVangLai))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiemTL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        pnTimTTKhachLayout.setVerticalGroup(
            pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim)))
                    .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNhapBill)
                            .addComponent(btnKHVangLai)))
                    .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13))
                        .addGroup(pnTimTTKhachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtLoaiKH, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                            .addGroup(pnTimTTKhachLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemTL)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBanhangLayout = new javax.swing.GroupLayout(pnBanhang);
        pnBanhang.setLayout(pnBanhangLayout);
        pnBanhangLayout.setHorizontalGroup(
            pnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTimTTKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnBanhangLayout.setVerticalGroup(
            pnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanhangLayout.createSequentialGroup()
                .addGroup(pnBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBanhangLayout.createSequentialGroup()
                        .addComponent(scpBan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnTimTTKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTop, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addComponent(pnBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addComponent(pnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbIconMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMenuMouseMoved
        // TODO add your handling code here:
        setLableBackgroundColor(lbIconMenu);
        pnQuanLy.setVisible(true);
    }//GEN-LAST:event_lbIconMenuMouseMoved

    private void lbIconMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMenuMouseExited
        resetLableBackgroundColor(lbIconMenu);
        if(press)
            pnQuanLy.setVisible(false);
    }//GEN-LAST:event_lbIconMenuMouseExited

    private void lbIconUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconUserMouseMoved
        // TODO add your handling code here:
        setLableBackgroundColor(lbIconUser);
    }//GEN-LAST:event_lbIconUserMouseMoved

    private void lbIconUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconUserMouseExited
        // TODO add your handling code here:
        resetLableBackgroundColor(lbIconUser);
    }//GEN-LAST:event_lbIconUserMouseExited

    private void lbIconExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconExitMouseMoved
        // TODO add your handling code here:
        setLableBackgroundColor(lbIconExit);
    }//GEN-LAST:event_lbIconExitMouseMoved

    private void lbIconExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconExitMouseExited
        // TODO add your handling code here:
        resetLableBackgroundColor(lbIconExit);
    }//GEN-LAST:event_lbIconExitMouseExited

    private void lbIconExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconExitMouseClicked
        // TODO add your handling code here:
        ThoatChuongTrinh thoat = new ThoatChuongTrinh(this,true);
        thoat.setVisible(true);
    }//GEN-LAST:event_lbIconExitMouseClicked

    private void pnQLSanPhamMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLSanPhamMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLSanPham);
    }//GEN-LAST:event_pnQLSanPhamMouseMoved

    private void pnQLSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLSanPhamMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLSanPham);
    }//GEN-LAST:event_pnQLSanPhamMouseExited

    private void pnQLHoaDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHoaDonMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLHoaDon);
    }//GEN-LAST:event_pnQLHoaDonMouseMoved

    private void pnQLHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHoaDonMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLHoaDon);
    }//GEN-LAST:event_pnQLHoaDonMouseExited

    private void pnQLNhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLNhanVienMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLNhanVien);
    }//GEN-LAST:event_pnQLNhanVienMouseMoved

    private void pnQLNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLNhanVienMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLNhanVien);
    }//GEN-LAST:event_pnQLNhanVienMouseExited

    private void pnQLKhachHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhachHangMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLKhachHang);
    }//GEN-LAST:event_pnQLKhachHangMouseMoved

    private void pnQLKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhachHangMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLKhachHang);
    }//GEN-LAST:event_pnQLKhachHangMouseExited

    private void pnDoanhThuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanhThuMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnDoanhThu);
    }//GEN-LAST:event_pnDoanhThuMouseMoved

    private void pnDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanhThuMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnDoanhThu);
    }//GEN-LAST:event_pnDoanhThuMouseExited

    private void pnQLKhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhoMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLKho);
    }//GEN-LAST:event_pnQLKhoMouseMoved

    private void pnQLKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhoMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLKho);
    }//GEN-LAST:event_pnQLKhoMouseExited

    private void lbIconMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMenuMousePressed
        // TODO add your handling code here:
        if(press){
            pnQuanLy.setVisible(false);
            press = false;
        }
        else{
            pnQuanLy.setVisible(true);
            press = true;
        }
    }//GEN-LAST:event_lbIconMenuMousePressed

    private void pnQLSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLSanPhamMouseClicked
        // TODO add your handling code here:
        if(quyen == 1 || quyen == 3){
            QL_SanPham form = new QL_SanPham();
            form.setVisible(true);
        }
    }//GEN-LAST:event_pnQLSanPhamMouseClicked

    private void pnQLHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLHoaDonMouseClicked
        // TODO add your handling code here:
        if(quyen == 1 || quyen == 2){
            QL_HoaDon form = new QL_HoaDon();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_pnQLHoaDonMouseClicked

    private void pnQLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLNhanVienMouseClicked
        // TODO add your handling code here:
        if(quyen == 1){
            QL_NhanVien form = new QL_NhanVien();
            form.setVisible(true);
        }
    }//GEN-LAST:event_pnQLNhanVienMouseClicked

    private void pnQLKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhachHangMouseClicked
        // TODO add your handling code here:
        if(quyen == 1 || quyen == 2 || quyen == 3){
            QL_KhachHang form = new QL_KhachHang();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_pnQLKhachHangMouseClicked

    private void pnDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanhThuMouseClicked
        // TODO add your handling code here:
        if(quyen == 1){
            QL_DoanhThu form = new QL_DoanhThu();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_pnDoanhThuMouseClicked

    private void pnQLKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLKhoMouseClicked
        // TODO add your handling code here:
        if(quyen == 1 || quyen == 3){
            QL_NhapXuatKho form = new QL_NhapXuatKho();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_pnQLKhoMouseClicked

    private void lbDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseMoved
        // TODO add your handling code here:
        setLableBackgroundColor(lbDangXuat);
    }//GEN-LAST:event_lbDangXuatMouseMoved

    private void lbDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseExited
        // TODO add your handling code here:
        resetLableBackgroundColor(lbDangXuat);
    }//GEN-LAST:event_lbDangXuatMouseExited

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked
        // TODO add your handling code here:
        int tb = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất tài khoản này không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(tb == JOptionPane.YES_OPTION){
            this.setVisible(false);
            LoginForm dangXuat = new LoginForm();
            dangXuat.setVisible(true);
        }
    }//GEN-LAST:event_lbDangXuatMouseClicked

    private void cboLoaiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiMonActionPerformed
        // TODO add your handling code here:
        
        for (LoaiHang loaiHang : lstLoaiHang) {
            if(loaiHang.getTenLoaiHang().equals(cboLoaiMon.getSelectedItem())){
                lstHang = SanPhamDAO.layDsSanPham(loaiHang.getMaLoai());
            }
                
        }
        cboMon.removeAllItems();
        for (SanPham sanPham : lstHang) {
            cboMon.addItem(sanPham.getTenHang());
        }
    }//GEN-LAST:event_cboLoaiMonActionPerformed

    private void pnQLDsBanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDsBanMouseMoved
        // TODO add your handling code here:
        setPanelBackgroundColor(pnQLDsBan);
    }//GEN-LAST:event_pnQLDsBanMouseMoved

    private void pnQLDsBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDsBanMouseClicked
        // TODO add your handling code here:
        if(quyen == 1){
            QL_Ban form = new QL_Ban();
            form.setVisible(true);
        }
        
    }//GEN-LAST:event_pnQLDsBanMouseClicked

    private void pnQLDsBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnQLDsBanMouseExited
        // TODO add your handling code here:
        resetPanelBackgroundColor(pnQLDsBan);
    }//GEN-LAST:event_pnQLDsBanMouseExited

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // Tìm khách hàng theo sdt và hiển thị thông tin
        if(txtSDT.getText() == null)
            JOptionPane.showConfirmDialog(null, "Nhập số điện thoại khách hàng để tìm thông tin!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        else{
            kh = KhachHangDAO.layKhachHang_theoSDT(txtSDT.getText());
            LoaiKhachHang lkh = new LoaiKhachHang();
            if(kh != null){
                lkh = KhachHangDAO.layLoaiKH(kh.getMaLoaiKH());
            }
            else{
                int temp = JOptionPane.showConfirmDialog(null, "Không tồn tại khách hàng trong danh sách thành viên của quán! Bạn có muốn thêm thành viên không?", "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
                if(temp == JOptionPane.YES_OPTION){
                    QL_KhachHang qlkh = new QL_KhachHang();
                    qlkh.setVisible(true);
                }
            }
            
            txtTenKH.setText(kh.getTenKH());
            txtLoaiKH.setText(lkh.getTenLoaiKH());
            txtDiemTL.setText(Integer.toString(kh.getDiemTL()));
        }
        
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnNhapBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapBillActionPerformed
        //Nếu tồn tại khách hàng thì tạo HOADON theo MaKH đó
        //Nếu không tồn tại khách hàng trong database thì hỏi xem có muốn thêm mới thành viên hay không hay là khách vãng lai
        //Nhập được HOADON mới cho bàn đó thì enable cho cboLoaiMon, cboMon
        
        boolean ktraTonTaiKH = KhachHangDAO.ktraSDT_KhachHang(txtSDT.getText());
        if( ktraTonTaiKH){
            int ktThemHoaDon = HoaDonDAO.themMoiHoaDon(new HoaDon(kh.getMaKH(), nv.getMaNV(), ban.get(0).getMaBan(), 0));
            boolean x = BanDAO.capNhapTrangThai(ban.get(0).getMaBan());
            moCombobox();
            loadDSBan();
        }
        else{
            int chon = JOptionPane.showConfirmDialog(null, "Khách hàng chưa là thành viên! Bạn có muốn thêm mới thành viên không?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (chon == JOptionPane.YES_OPTION){
                QL_KhachHang formKhachHang = new QL_KhachHang();
                formKhachHang.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_btnNhapBillActionPerformed

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        // reset lại textbox và xóa dữ liệu của khách hàng (biến kh) đã được tìm trước đó
        txtSDT.setText("");
        kh = new KhachHang();
    }//GEN-LAST:event_txtSDTFocusGained

    private void btnKHVangLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHVangLaiActionPerformed
        // Thêm mới hóa đơn với MaKH là KH000 (khách vãng lai)
        int ktThemHoaDon = HoaDonDAO.themMoiHoaDon(new HoaDon("KH000", nv.getMaNV(), ban.get(0).getMaBan(), 0));
        boolean x = BanDAO.capNhapTrangThai(ban.get(0).getMaBan());
        moCombobox();
        loadDSBan();
    }//GEN-LAST:event_btnKHVangLaiActionPerformed
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        HoaDon hd = new HoaDon();
        hd = HoaDonDAO.layHoaDon(ban.get(0).getMaBan());
        String mahang = "";
        String tenHang = "";
        tenHang = cboMon.getSelectedItem().toString();
        for(int i = 0; i < lstHang.size(); i++){
            if(lstHang.get(i).getTenHang().equalsIgnoreCase(tenHang))
                mahang = lstHang.get(i).getMaHang();
        }
        BigDecimal donGia = SanPhamDAO.layGiaSP(mahang);
        ChiTietHoaDon ct = new ChiTietHoaDon(hd.getMaHD(), mahang, (int)SoluongMon.getValue(), donGia);
        ChiTietHoaDonDAO.themMoiChiTietHD(ct);
        hienThiDsGoiMon(ban.get(0).getMaBan());
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double tienThua = Double.parseDouble(txtTienKhachDua.getText()) - Double.parseDouble(lbTongTien.getText());
        lbTienThua.setText(tienThua.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        hd_DaThanhToan = HoaDonDAO.layHoaDon(ban.get(0).getMaBan());
        int x = HoaDonDAO.capNhatTrangThai(hd_DaThanhToan.getMaHD());
        if (x >= 1){
            JOptionPane.showMessageDialog(null, String.format("Thanh toán thành công bàn %s",ban.get(0).getMaBan()), "Thông báo",JOptionPane.INFORMATION_MESSAGE);
            loadDSBan();
        }
        else
        {
            JOptionPane.showMessageDialog(null, String.format("Thanh toán không thành công bàn %s",ban.get(0).getMaBan()), "Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnInHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnInHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SoluongMon;
    private javax.swing.JButton btnInHD;
    private javax.swing.JButton btnKHVangLai;
    private javax.swing.JButton btnNhapBill;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cboLoaiMon;
    private javax.swing.JComboBox<String> cboMon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbIconBieuDo;
    private javax.swing.JLabel lbIconBieuDo1;
    private javax.swing.JLabel lbIconCafe;
    private javax.swing.JLabel lbIconDoAn;
    private javax.swing.JLabel lbIconExit;
    private javax.swing.JLabel lbIconKH;
    private javax.swing.JLabel lbIconKho1;
    private javax.swing.JLabel lbIconMenu;
    private javax.swing.JLabel lbIconNV;
    private javax.swing.JLabel lbIconUser;
    private javax.swing.JLabel lbKho1;
    private javax.swing.JLabel lbQLDoAn;
    private javax.swing.JLabel lbQLDoUong;
    private javax.swing.JLabel lbQLKH;
    private javax.swing.JLabel lbQLNV;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbThongKe1;
    private javax.swing.JLabel lbTienThua;
    private javax.swing.JLabel lbTimer;
    private javax.swing.JLabel lbTitleTienThua;
    private javax.swing.JLabel lbTitleTongTien;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JPanel pnBanhang;
    private javax.swing.JPanel pnChuyenBan;
    private javax.swing.JPanel pnDoanhThu;
    private javax.swing.JPanel pnDsMonDaGoi;
    private javax.swing.JPanel pnGhiChu;
    private javax.swing.JPanel pnQLBan;
    private javax.swing.JPanel pnQLDsBan;
    private javax.swing.JPanel pnQLHoaDon;
    private javax.swing.JPanel pnQLKhachHang;
    private javax.swing.JPanel pnQLKho;
    private javax.swing.JPanel pnQLNhanVien;
    private javax.swing.JPanel pnQLSanPham;
    private javax.swing.JPanel pnQuanLy;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThanhToan;
    private javax.swing.JPanel pnThemMon;
    private javax.swing.JPanel pnTimTTKhach;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane scpBan;
    private javax.swing.JScrollPane scpCacMon;
    private javax.swing.JTable tblCacMon;
    private javax.swing.JTextField txtDiemTL;
    private javax.swing.JTextField txtLoaiKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienKhachDua;
    // End of variables declaration//GEN-END:variables


    @Override
    public void run() {
        while(true){
            Calendar cal = Calendar.getInstance();
        
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
            Date d = cal.getTime();
            String time = sdf.format(d);
            
            lbTimer.setText(time);
        }
    }

    private void setDisplay() {
        this.setSize(890, 820);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        pnQLBan.setPreferredSize(new Dimension(395, MAXIMIZED_VERT));
        scpBan.setViewportView(pnQLBan);
        
    }
    
    private void setLableBackgroundColor(JLabel lb){
        lb.setBackground(new Color(235,184,50)); //235,184,50 235,151,100
    }
    
    private void resetLableBackgroundColor(JLabel lb){
        lb.setBackground(new Color(235,151,100));
    }
    
    private void setPanelBackgroundColor(JPanel pn){
        pn.setBackground(new Color(50,57,186));
        pn.setBorder(BorderFactory.createMatteBorder(0, 0, 4, 0,Color.WHITE));
    }
    
    private void resetPanelBackgroundColor(JPanel pn){
        pn.setBackground(new Color(50,67,95));
        pn.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 0,Color.WHITE));
    }

    private void loadDSBan() {
        lstBan = BanDAO.layDsBan("");
        
        pnQLBan.setLayout(new FlowLayout(FlowLayout.CENTER, 10,10));
        if(lstBan != null){
            pnQLBan.removeAll();
            JButton[] btn = new JButton[lstBan.size()];
            for (int i = 0; i < lstBan.size(); i++){
                btn[i] = new JButton();
                //Set các thuộc tính của btn
                btn[i].setName(String.valueOf(lstBan.get(i).getMaBan()));
                String[] mb = lstBan.get(i).getTenBan().split(" ");
                btn[i].setText(mb[1]);
                btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_table.png")));
                Border thickBorder = new LineBorder(Color.WHITE,8);
                btn[i].setBorder(thickBorder);
                btn[i].setBackground(Color.decode("#8080ff"));
                btn[i].setFont(new java.awt.Font("Tahoma", 1, 10));
                btn[i].setForeground(new java.awt.Color(51, 51, 51));
                btn[i].setPreferredSize(new Dimension(90, 70));
                
                //đổi màu cho bàn đang phục vụ
                String tt = lstBan.get(i).getTrangThai();
                if(tt.equals("Đang phục vụ")){
                    btn[i].setBackground(Color.decode("#66ff66"));
                }
                
                
                btn[i].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
                            dongComboBox();
                            ban = BanDAO.layDsBan(e.getComponent().getName());
                            if(ban != null){
                                if(ban.get(0).getTrangThai().equals("Đang phục vụ"))
                                    hienThiDsGoiMon(ban.get(0).getMaBan());
                                else
                                    dtm.setNumRows(0);
                            }
                            moCombobox();
                            
                            //set viền cho btn
                            Border setLineBd = new LineBorder(Color.black, 8);
                            btn[Integer.parseInt(String.valueOf(e.getComponent().getName().substring(2))) - 1].setBorder(setLineBd);
                            
                            //reset viền cho btn đã nhấn trước đó
                            if(btnPrevPress != -1){
                                Border resetLineBd = new LineBorder(Color.white, 8);
                                btn[btnPrevPress].setBorder(resetLineBd);
                            }
                            //Lưu lại vị trí của btn đã nhấn trước đó
                            btnPrevPress = Integer.parseInt(String.valueOf(e.getComponent().getName().substring(2))) - 1;
                        }
                });
                
                pnQLBan.add(btn[i]);
                pnQLBan.updateUI();
            }
        }
    }
    


    private void hienThiDsGoiMon(String maBan){
        dtm.setNumRows(0);
        // Lấy danh sách món đã gọi
        lstMon = new ArrayList<>();
        HoaDon hd = new HoaDon();
        hd = HoaDonDAO.layHoaDon(maBan);
        lstMon = ChiTietHoaDonDAO.layDsGoiMon(hd.getMaHD());
        
        for(int i = 0; i < lstMon.size(); i++){
            Vector<Object> mon = new Vector<>();
            
            mon.add(i + 1);
            mon.add(lstMon.get(i).getTenHang());
            mon.add(lstMon.get(i).getDonGia());
            mon.add(lstMon.get(i).getSoLuong());
            mon.add(lstMon.get(i).getSoLuong() * lstMon.get(i).getDonGia().doubleValue());
            
            dtm.addRow(mon);
        }

        capNhatTongTien(hd);
    }
    
    private void loadMon() {
        
        lstLoaiHang = LoaiHangDAO.layDsLoaiHang();
        // load combobox loai hang
        for (LoaiHang loaiHang : lstLoaiHang) {
            cboLoaiMon.addItem(loaiHang.getTenLoaiHang());
        }
        
        
    }

    //Enable cho cboMon,cboLoaiHang
    private void moCombobox(){
        HoaDon hd = new HoaDon();
        hd = HoaDonDAO.layHoaDon(ban.get(0).getMaBan());
        if(hd != null){
            if(hd.getTrangThai() == 0){
                cboLoaiMon.setEnabled(true);
                cboMon.setEnabled(true);
            }
        }
        
    }
    
    private void dongComboBox(){
        cboLoaiMon.setEnabled(false);
        cboMon.setEnabled(false);
    }

    private void capNhatTongTien(HoaDon hd) {
        lbTongTien.setText(hd.getTongThanhTien().toString());
    }

    private void phanQuyen() {
        if(Run.tk.getPhanQuyen() == 2){
            pnQLDsBan.setEnabled(false);
            pnQLSanPham.setEnabled(false);
            pnQLNhanVien.setEnabled(false);
            pnQLKho.setEnabled(false);
        }
        else if(Run.tk.getPhanQuyen() == 3){
            pnQLHoaDon.setEnabled(false);
            pnDoanhThu.setEnabled(false);
            pnQLDsBan.setEnabled(false);
            pnQLNhanVien.setEnabled(false);
        }
    }

  
}
