/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.KhachHangDAO;
import dao.LoaiKhachHangDAO;
import dao.TaiKhoanDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.KhachHang;
import pojo.TaiKhoan;

/**
 *
 * @author PC
 */
public class QL_KhachHang extends javax.swing.JFrame {
    Statement statement = null;
    PreparedStatement preStatement = null;
    Connection connection = null;
    ResultSet resultset = null;
    //DefaultTableModel dtm = new DefaultTableModel();
    
     ArrayList<KhachHang> lstKH = new ArrayList<>();
    /**
     * Creates new form QL_KhachHang
     */
    public QL_KhachHang() {
        initComponents();
        loadDisplay();
        
        loadTableInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThongTinKH = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        lbMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lbSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtMaLoaiKH = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lbMaKH1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnDSKhachHang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnThongTinKH.setBackground(new java.awt.Color(50, 67, 95));
        pnThongTinKH.setForeground(new java.awt.Color(255, 255, 102));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 102));
        lbTitle.setText("Thông tin khách hàng thành viên");

        pnRight.setBackground(new java.awt.Color(50, 67, 95));

        lbMaKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaKH.setForeground(new java.awt.Color(255, 255, 255));
        lbMaKH.setText("Mã khách hàng");

        txtMaKH.setBackground(new java.awt.Color(50, 67, 95));
        txtMaKH.setForeground(new java.awt.Color(255, 255, 255));
        txtMaKH.setText("Nhập mã nhân viên");
        txtMaKH.setBorder(null);
        txtMaKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaKHFocusGained(evt);
            }
        });

        lbHoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen.setText("Họ và tên");

        txtHoTen.setBackground(new java.awt.Color(50, 67, 95));
        txtHoTen.setForeground(new java.awt.Color(255, 255, 255));
        txtHoTen.setText("Nhập họ tên");
        txtHoTen.setBorder(null);
        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoTenFocusGained(evt);
            }
        });

        lbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        lbDiaChi.setText("Địa chỉ");

        txtDiaChi.setBackground(new java.awt.Color(50, 67, 95));
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setText("Nhập địa chỉ");
        txtDiaChi.setBorder(null);
        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusGained(evt);
            }
        });

        lbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSDT.setForeground(new java.awt.Color(255, 255, 255));
        lbSDT.setText("SĐT");

        txtSDT.setBackground(new java.awt.Color(50, 67, 95));
        txtSDT.setForeground(new java.awt.Color(255, 255, 255));
        txtSDT.setText("Nhập số điện thoại");
        txtSDT.setBorder(null);
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSDTFocusGained(evt);
            }
        });

        txtMaLoaiKH.setBackground(new java.awt.Color(50, 67, 95));
        txtMaLoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        txtMaLoaiKH.setBorder(null);
        txtMaLoaiKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaLoaiKHFocusGained(evt);
            }
        });

        lbMaKH1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaKH1.setForeground(new java.awt.Color(255, 255, 255));
        lbMaKH1.setText("Loại khách hàng");

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator7)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbMaKH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator9)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addComponent(txtMaLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addComponent(lbSDT)
                        .addGap(38, 38, 38)
                        .addComponent(lbMaKH1))
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(59, 23));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(59, 23));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(59, 23));

        javax.swing.GroupLayout pnThongTinKHLayout = new javax.swing.GroupLayout(pnThongTinKH);
        pnThongTinKH.setLayout(pnThongTinKHLayout);
        pnThongTinKHLayout.setHorizontalGroup(
            pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinKHLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnThongTinKHLayout.setVerticalGroup(
            pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        pnDSKhachHang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(59, 23));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ tên", "SĐT", "Địa chỉ", "Điểm tích lũy", "Loại khách hàng", "Chiết khấu"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        javax.swing.GroupLayout pnDSKhachHangLayout = new javax.swing.GroupLayout(pnDSKhachHang);
        pnDSKhachHang.setLayout(pnDSKhachHangLayout);
        pnDSKhachHangLayout.setHorizontalGroup(
            pnDSKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        pnDSKhachHangLayout.setVerticalGroup(
            pnDSKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTinKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnDSKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusGained
        // TODO add your handling code here:
        txtSDT.setText("");
    }//GEN-LAST:event_txtSDTFocusGained

    private void txtDiaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusGained
        // TODO add your handling code here:
        txtDiaChi.setText("");
    }//GEN-LAST:event_txtDiaChiFocusGained

    private void txtHoTenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusGained
        // TODO add your handling code here:
        txtHoTen.setText("");
    }//GEN-LAST:event_txtHoTenFocusGained

    private void txtMaKHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKHFocusGained
        // TODO add your handling code here:
        txtMaKH.setText("");
    }//GEN-LAST:event_txtMaKHFocusGained

    private void txtMaLoaiKHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLoaiKHFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiKHFocusGained

    //ThemKH
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
         if(KhachHangDAO.ktraKHCoTonTai(txtMaKH.getText())== false){
            try {
                KhachHang kh = new KhachHang();
                kh.setMaKH(txtMaKH.getText());
                kh.setTenKH(txtHoTen.getText());
                kh.setSDT(txtSDT.getText());
                kh.setDiaChi(txtDiaChi.getText());
                kh.setMaLoaiKH(txtMaLoaiKH.getText());
            
                
                boolean result = false;
                if(KhachHangDAO.ktraSDT_KhachHang(txtSDT.getText())){
                    JOptionPane.showConfirmDialog(null, "SDT không được trùng", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                
                }else{
                    result = KhachHangDAO.themKhachHang(kh);
                }
                
                if(result == false){
                    JOptionPane.showConfirmDialog(null, "Thêm thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
                else{
                    loadTableInfo();
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Mã kh nhập bị trùng, bạn có muốn chỉnh sửa thông tin nv không?", "Thông báo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                try {
                    
                    KhachHang kh = new KhachHang();
  //                  KhachHang kh = new KhachHang(txtMaKH.getText(),txtHoTen.getText(), txtSDT.getText(), txtDiaChi.getText(), txtMaKH1.getText());
                   kh.setMaKH(txtMaKH.getText());
                   kh.setTenKH(txtHoTen.getText());
                   kh.setSDT(txtSDT.getText());
                   kh.setDiaChi(txtDiaChi.getText());
                   kh.setMaLoaiKH(txtMaLoaiKH.getText());
                    boolean result = KhachHangDAO.capNhatThongTin_KhachHang(kh);
                    
                    if(result == false)
                        JOptionPane.showConfirmDialog(null, "Cập nhật thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    else{
                        loadTableInfo();
                        JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }



    }//GEN-LAST:event_btnThemActionPerformed

    //Xóa KH
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        boolean result = KhachHangDAO.xoa1Khachhang(txtMaKH.getText());
        try {
           
            if(result == false)
                JOptionPane.showConfirmDialog(null, "Xóa thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            else{
                JOptionPane.showConfirmDialog(null, "Xóa thành công!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfo();
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        boolean ktraTrung_MaKH = KhachHangDAO.ktraKHCoTonTai(txtMaKH.getText());
        
        KhachHang kh = new KhachHang();
        if(ktraTrung_MaKH == true){
            kh.setMaKH(txtMaKH.getText());
            kh.setTenKH(txtHoTen.getText());
            kh.setSDT(txtSDT.getText());
            kh.setDiaChi(txtDiaChi.getText());
            kh.setMaLoaiKH(txtMaLoaiKH.getText());
           
            boolean kq = KhachHangDAO.capNhatThongTin_KhachHang(kh);
            if(kq){
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin khách hàng có mã %s thành công!!!!",txtMaKH.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfo();
            }
            else{
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin khách hàng có mã %s không thành công!!!!",txtMaKH.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            }
        }
        else{
            int temp = JOptionPane.showConfirmDialog(null, "Mã Khách Hàng không tồn tại trong danh sách, bạn có muốn thêm mới khách hàng không?","Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_OPTION);
            if(temp == JOptionPane.YES_OPTION){
                kh.setMaKH(txtMaKH.getText());
                kh.setTenKH(txtHoTen.getText());
                kh.setSDT(txtSDT.getText());
                kh.setDiaChi(txtDiaChi.getText());
                kh.setMaLoaiKH(txtMaLoaiKH.getText());
                               
                boolean kq = KhachHangDAO.themKhachHang(kh);
                if(kq){
                    JOptionPane.showConfirmDialog(null, "Thêm Khách hàng thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    loadTableInfo();
                }
                else{
                    JOptionPane.showConfirmDialog(null, "Thêm Khách hàng không thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        int row = tblKhachHang.getSelectedRow();

        txtHoTen.setText(tblKhachHang.getValueAt(row, 1).toString());
        txtSDT.setText(tblKhachHang.getValueAt(row, 2).toString());
        txtDiaChi.setText(tblKhachHang.getValueAt(row, 3).toString());
        txtMaLoaiKH.setText(tblKhachHang.getValueAt(row, 5).toString());
        txtMaKH.setText(tblKhachHang.getValueAt(row, 0).toString());

    }//GEN-LAST:event_tblKhachHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMaKH;
    private javax.swing.JLabel lbMaKH1;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pnDSKhachHang;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThongTinKH;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaLoaiKH;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables

    private void loadDisplay() {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Quản lý khách hàng");
    }

    //DanhSachKH
    private void loadTableInfo() {

        lstKH = KhachHangDAO.layDSKhachHang();
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel)tblKhachHang.getModel();
        
                
        dtm.setNumRows(0);
        for(KhachHang kh : lstKH){
            Vector<Object> khachhang = new Vector<>();
            float tyLeGiamGia = LoaiKhachHangDAO.layTyLeGiamGia(kh.getMaLoaiKH());
            
            khachhang.add(kh.getMaKH());
            khachhang.add(kh.getTenKH());
            khachhang.add(kh.getSDT());
            khachhang.add(kh.getDiaChi());
            khachhang.add(kh.getDiemTL());
            khachhang.add(kh.getMaLoaiKH());
            khachhang.add(tyLeGiamGia);
            
            dtm.addRow(khachhang);
        }
        
        
    }
     
}
