/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.ChiTietPhieuNhapDAO;
import dao.ChiTietPhieuXuatDAO;
import dao.NguyenLieuDAO;
import dao.NhaCungCapDAO;
import dao.PhieuNhapDAO;
import dao.PhieuXuatDAO;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.Run;
import pojo.ChiTietPhieuNhap;
import pojo.ChiTietPhieuXuat;
import pojo.NguyenLieu;
import pojo.NhaCungCap;
import pojo.PhieuNhap;
import pojo.PhieuXuat;

/**
 *
 * @author PC
 */
public class QL_NhapXuatKho extends javax.swing.JFrame {

    ArrayList<NguyenLieu> lstNguyenLieu = new ArrayList<>();
    ArrayList<NhaCungCap> lstNhaCC = new ArrayList<>();
    ArrayList<PhieuNhap> lstPhieuNhap = new ArrayList<>();
    ArrayList<PhieuXuat> lstPhieuXuat = new ArrayList<>();
    ArrayList<NguyenLieu> lstNL = new ArrayList<NguyenLieu>();
    DefaultTableModel dtm1, dtm2, dtm3, dtm4 = new DefaultTableModel();
    public QL_NhapXuatKho() {
        initComponents();
        loadDisplay();
        loadCombobox();
        dtm1 = (DefaultTableModel)tblThongTinNhap.getModel();
        dtm2 = (DefaultTableModel)tblThongTinNhap1.getModel();
        loadTableInfo_NhapKho();
        
        dtm3 = (DefaultTableModel)tblThongTinXuat.getModel();
        dtm4 = (DefaultTableModel)tblThongTinXuat1.getModel();
        loadTableInfo_XuatKho();
        
        loadTableInfo_NguyenLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnNhap = new javax.swing.JPanel();
        pnNhapDuLieu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboMaNguyenLieu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboMaNhaCC = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMaNV1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGhiChu1 = new java.awt.TextArea();
        jLabel11 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSoLuong1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnThemMatHang = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinNhap = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongTinNhap1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        pnXuat = new javax.swing.JPanel();
        pnXuatDuLieu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboTenNguyenLieu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong2 = new javax.swing.JSpinner();
        txtMaNV2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNgayXuat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtGhiChu2 = new java.awt.TextArea();
        jPanel6 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnThemMatHang2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThongTinXuat = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThongTinXuat1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pnMain = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNguyenLieu = new javax.swing.JTable();
        pnThongTin = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMaNL = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtTenNL = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pnTimKiem = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(182, 214, 247));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnNhap.setBackground(new java.awt.Color(182, 214, 247));

        pnNhapDuLieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnNhapDuLieu.setOpaque(false);

        jLabel2.setText("Mã Nguyên Liệu");

        jLabel3.setText("Mã nhà cung cấp");

        jLabel4.setText("Ngày Nhập Kho");

        txtMaNV1.setEnabled(false);

        jLabel10.setText("Ghi chú");

        jLabel11.setText("Mã nhân viên");

        txtNgayNhap.setText("dd/mm/yyy");
        txtNgayNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayNhapMouseClicked(evt);
            }
        });

        jLabel12.setText("Số lượng");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm thông tin sản phẩm muốn nhập kho");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setOpaque(false);

        btnThem1.setText("Thêm mới");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa mặt hàng");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnThemMatHang.setText("Thêm mặt hàng");
        btnThemMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMatHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem1)
                .addGap(28, 28, 28)
                .addComponent(btnThemMatHang)
                .addGap(31, 31, 31)
                .addComponent(btnXoa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSua1)
                .addContainerGap())
        );

        jLabel18.setText("Giá nhập");

        txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNhapDuLieuLayout = new javax.swing.GroupLayout(pnNhapDuLieu);
        pnNhapDuLieu.setLayout(pnNhapDuLieuLayout);
        pnNhapDuLieuLayout.setHorizontalGroup(
            pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMaNguyenLieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboMaNhaCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNhapDuLieuLayout.setVerticalGroup(
            pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMaNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboMaNhaCC, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhapDuLieuLayout.createSequentialGroup()
                                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnNhapDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setOpaque(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setOpaque(false);

        tblThongTinNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Mã nhà cung cấp", "Ngày Nhập", "Ghi chú", "Tiền nhập", "Mã nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTinNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTinNhap);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("THÔNG TIN PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner2.png"))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setOpaque(false);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setOpaque(false);

        tblThongTinNhap1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Mã Nguyên Liệu", "Tên nguyên liệu", "Số Lượng", "Giá nhập", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongTinNhap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinNhap1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThongTinNhap1);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("CHI TIẾT PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnNhapLayout = new javax.swing.GroupLayout(pnNhap);
        pnNhap.setLayout(pnNhapLayout);
        pnNhapLayout.setHorizontalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnNhapDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnNhapLayout.setVerticalGroup(
            pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhapLayout.createSequentialGroup()
                        .addComponent(pnNhapDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhập kho", pnNhap);

        pnXuat.setBackground(new java.awt.Color(157, 85, 17));

        pnXuatDuLieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnXuatDuLieu.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm thông tin sản phẩm muốn xuất kho");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên nguyên liệu");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số lượng");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mã nhân viên");

        txtMaNV2.setEnabled(false);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ngày xuất");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ghi chú");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setOpaque(false);

        btnThem2.setText("Thêm mới phiếu");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXoa2.setText("Xóa mặt hàng");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        btnThemMatHang2.setText("Thêm mặt hàng");
        btnThemMatHang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMatHang2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemMatHang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem2)
                .addGap(28, 28, 28)
                .addComponent(btnThemMatHang2)
                .addGap(31, 31, 31)
                .addComponent(btnXoa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSua2)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnXuatDuLieuLayout = new javax.swing.GroupLayout(pnXuatDuLieu);
        pnXuatDuLieu.setLayout(pnXuatDuLieuLayout);
        pnXuatDuLieuLayout.setHorizontalGroup(
            pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                        .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboTenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnXuatDuLieuLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNgayXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnXuatDuLieuLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaNV2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnXuatDuLieuLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnXuatDuLieuLayout.setVerticalGroup(
            pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnXuatDuLieuLayout.createSequentialGroup()
                                .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cboTenNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtMaNV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtGhiChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnXuatDuLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtNgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setOpaque(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblThongTinXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu xuất", "Mã nhân viên", "Ngày xuất", "Ghi chú"
            }
        ));
        tblThongTinXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinXuatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThongTinXuat);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Danh sách phiếu xuất");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner1.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblThongTinXuat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã phiếu xuất", "Mã nguyên liệu", "Tên nguyên liệu", "Số lượng"
            }
        ));
        jScrollPane4.setViewportView(tblThongTinXuat1);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Thông tin chi tiết phiếu xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout pnXuatLayout = new javax.swing.GroupLayout(pnXuat);
        pnXuat.setLayout(pnXuatLayout);
        pnXuatLayout.setHorizontalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnXuatDuLieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnXuatLayout.setVerticalGroup(
            pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(pnXuatDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnXuatLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Xuất kho", pnXuat);

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));

        pnMain.setOpaque(false);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nguyên Liệu", "Tên Nguyên Liệu", "DVT", "Số Lượng"
            }
        ));
        tblNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblNguyenLieu);

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnThongTin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnThongTin.setOpaque(false);

        jLabel21.setText("DVT");

        jLabel22.setText("Tên Nguyên Liệu");

        jLabel23.setText("Mã Nguyên Liệu");

        jLabel24.setText("Số Lượng");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Thông tin nguyên liệu trong kho");

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnThongTinLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnThongTinLayout.createSequentialGroup()
                            .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(72, 72, 72)
                            .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaNL, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTenNL, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel25))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDVT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTimKiem.setOpaque(false);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("Tìm Kiếm");

        btnTim.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnTimKiemLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnTimKiemLayout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTim)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTim)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnReset)
                    .addComponent(btnSua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nguyên liệu trong kho", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayNhapMouseClicked
        txtNgayNhap.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayNhapMouseClicked

    private void tblThongTinNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinNhapMouseClicked
        // TODO add your handling code here:
        
        loadCTPN(tblThongTinNhap.getValueAt(tblThongTinNhap.getSelectedRow(), 0).toString());
        
        txtMaNV1.setText(tblThongTinNhap.getValueAt(tblThongTinNhap.getSelectedRow(), 5).toString()); 
        
        txtNgayNhap.setText(tblThongTinNhap.getValueAt(tblThongTinNhap.getSelectedRow(), 2).toString());
        
        for(NhaCungCap ncc : lstNhaCC){
            if(ncc.getMaNCC().equals(tblThongTinNhap.getValueAt(tblThongTinNhap.getSelectedRow(), 1).toString())){
                cboMaNhaCC.setSelectedItem(ncc.getMaNCC());
            }
        }
    }//GEN-LAST:event_tblThongTinNhapMouseClicked

    private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaNhapActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        PhieuNhap pn = new PhieuNhap(cboMaNhaCC.getSelectedItem().toString(), Run.tk.getMaNV(), txtGhiChu1.getText());
        boolean temp = PhieuNhapDAO.themMoiPhieuNhap(pn);
        if(temp == true){
            JOptionPane.showMessageDialog(null, "Thêm mới phiếu nhập thành công");
            loadTableInfo_NhapKho();
        }
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnThemMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMatHangActionPerformed
        // TODO add your handling code here:
        if (txtGiaNhap.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập giá nhập!");
                txtGiaNhap.setFocusable(true);
        }
            
        if ((int)txtSoLuong1.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập số lượng nhập!");
            txtSoLuong1.setFocusable(true);
        }
        
        int row = tblThongTinNhap.getSelectedRow();
        if (row != -1){
            String manl = cboMaNguyenLieu.getSelectedItem().toString();
            ChiTietPhieuNhap ct = new ChiTietPhieuNhap(tblThongTinNhap.getValueAt(row, 0).toString(), manl, NguyenLieuDAO.layTenNguyenLieu(manl), Integer.parseInt(txtSoLuong1.getValue().toString()), BigDecimal.valueOf(Double.parseDouble(txtGiaNhap.getText())),BigDecimal.ZERO);
            boolean temp = ChiTietPhieuNhapDAO.themMoiCTPN(ct);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Thêm thành công chi tiết phiếu nhập");
                loadTableInfo_NhapKho();
                loadCTPN(tblThongTinNhap.getValueAt(row, 0).toString());
                loadTableInfo_NguyenLieu();
            }
            else{
                JOptionPane.showMessageDialog(null, "Thêm thất bại chi tiết phiếu nhập");
            }
        }
        else{
            int x = JOptionPane.showConfirmDialog(null, "Bạn chưa chọn phiếu nhập muốn nhập nguyên liệu, bạn có muốn thêm mới phiếu nhập không", "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(x == JOptionPane.YES_OPTION){
                PhieuNhap pn = new PhieuNhap(cboMaNhaCC.getSelectedItem().toString(), Run.tk.getMaNV(), txtGhiChu1.getText());
                boolean temp = PhieuNhapDAO.themMoiPhieuNhap(pn);
                if(temp == true){
                    JOptionPane.showMessageDialog(null, "Thêm mới phiếu nhập thành công");
                    loadTableInfo_NhapKho();
                }
            }
        }
        
    }//GEN-LAST:event_btnThemMatHangActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        int row = tblThongTinNhap1.getSelectedRow();
            
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn chi tiết phiếu nhập muốn xóa!");
        }
        else{
            ChiTietPhieuNhap ct = new ChiTietPhieuNhap(tblThongTinNhap1.getValueAt(row, 0).toString(), tblThongTinNhap1.getValueAt(row, 1).toString());
            boolean temp = ChiTietPhieuNhapDAO.xoa1CTPN(ct);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                loadTableInfo_NhapKho();
                loadCTPN(ct.getMaPN());
                loadTableInfo_NguyenLieu();
            }
            else
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        if(tblThongTinNhap.getSelectedRow() > -1){
            PhieuNhap pn = new PhieuNhap(tblThongTinNhap.getValueAt(tblThongTinNhap.getSelectedRow(), 0).toString(), cboMaNhaCC.getSelectedItem().toString(),"", txtGhiChu1.getText(),BigDecimal.ZERO,Date.valueOf(LocalDate.MAX));
            boolean temp = PhieuNhapDAO.capNhatPhieuNhap(pn);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu nhập thành công");
                loadTableInfo_NhapKho();
                loadTableInfo_NguyenLieu();
            }
            else
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu nhập thất bại");
        }
        else if(tblThongTinNhap1.getSelectedRow() > -1){
            int soluong = Integer.parseInt(txtSoLuong1.getValue().toString());
            if(soluong == 0){
                soluong = Integer.parseInt(tblThongTinNhap1.getValueAt(tblThongTinNhap1.getSelectedRow(), 3).toString());
            }
                
            ChiTietPhieuNhap ct = new ChiTietPhieuNhap(tblThongTinNhap1.getValueAt(tblThongTinNhap1.getSelectedRow(), 0).toString(), tblThongTinNhap1.getValueAt(tblThongTinNhap1.getSelectedRow(), 1).toString(), soluong, BigDecimal.valueOf(Double.parseDouble(txtGiaNhap.getText())));
            boolean temp = ChiTietPhieuNhapDAO.capNhatCTPN(ct);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Cập nhật chi tiết phiếu nhập thành công");
                loadTableInfo_NhapKho();
                loadCTPN(ct.getMaPN());
                loadTableInfo_NguyenLieu();
            }
            else
                JOptionPane.showMessageDialog(null, "Cập nhật chi tiết phiếu nhập thất bại");
        }   
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void tblThongTinNhap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinNhap1MouseClicked
        // TODO add your handling code here:
        tblThongTinNhap.clearSelection();
    }//GEN-LAST:event_tblThongTinNhap1MouseClicked

    private void tblThongTinXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinXuatMouseClicked
        // TODO add your handling code here:
        int row = tblThongTinXuat.getSelectedRow();
        loadCTPX(tblThongTinXuat.getValueAt(row, 0).toString());
        
        txtMaNV2.setText(tblThongTinXuat.getValueAt(row, 1).toString());
        txtGhiChu2.setText(tblThongTinXuat.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblThongTinXuatMouseClicked

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
        PhieuXuat px = new PhieuXuat("NV001", txtGhiChu2.getText());
        boolean temp = PhieuXuatDAO.themMoiPhieuXuat(px);
        if(temp == true){
            JOptionPane.showMessageDialog(null, "Thêm mới phiếu xuất thành công");
            loadTableInfo_XuatKho();
        }
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        int row = tblThongTinXuat1.getSelectedRow();
            
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn chi tiết phiếu xuất muốn xóa!");
        }
        else{
            ChiTietPhieuXuat ct = new ChiTietPhieuXuat(tblThongTinXuat1.getValueAt(row, 0).toString(), tblThongTinXuat1.getValueAt(row, 1).toString());
            boolean temp = ChiTietPhieuXuatDAO.xoa1CTPX(ct);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                loadTableInfo_XuatKho();
                loadCTPX(ct.getMaPX());
                loadTableInfo_NguyenLieu();
            }
            else
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
        if(tblThongTinXuat.getSelectedRow() > -1){
            PhieuXuat px = new PhieuXuat(tblThongTinXuat.getValueAt(tblThongTinXuat.getSelectedRow(), 0).toString() ,txtMaNV2.getText(), txtGhiChu2.getText(),Date.valueOf(LocalDate.MAX));
            boolean temp = PhieuXuatDAO.capNhatPhieuXuat(px);
            if(temp == true){
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu xuất thành công");
                loadTableInfo_XuatKho();
            }
            else
                JOptionPane.showMessageDialog(null, "Cập nhật phiếu xuất thất bại");
        }
        else if(tblThongTinXuat1.getSelectedRow() > -1){
            int soluong = Integer.parseInt(txtSoLuong2.getValue().toString());
            int row = tblThongTinXuat1.getSelectedRow();
            if(soluong == 0){
                soluong = Integer.parseInt(tblThongTinXuat1.getValueAt(row, 3).toString());
            }
            int hoi = JOptionPane.showConfirmDialog(null, String.format(
                    "Bạn có muốn sửa chi tiết phiếu xuất với nguyên liệu %s và số lượng %s được lưu trong phiếu xuất %s không", cboTenNguyenLieu.getSelectedItem().toString(), soluong, tblThongTinXuat1.getValueAt(row, 0)),
                    "Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.YES_NO_OPTION);
            if(hoi == JOptionPane.YES_OPTION){
                ChiTietPhieuXuat ct = new ChiTietPhieuXuat(tblThongTinXuat1.getValueAt(row, 0).toString(), tblThongTinXuat1.getValueAt(row, 1).toString(), cboTenNguyenLieu.getSelectedItem().toString(),soluong);

                boolean temp = ChiTietPhieuXuatDAO.capNhatCTPX(ct);
                if(temp == true){
                    JOptionPane.showMessageDialog(null, "Cập nhật chi tiết phiếu xuất thành công");
                    loadTableInfo_XuatKho();
                    loadCTPX(ct.getMaPX());
                    loadTableInfo_NguyenLieu();
                }
                else
                    JOptionPane.showMessageDialog(null, "Cập nhật chi tiết phiếu xuất thất bại");
            }
        }   
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnThemMatHang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMatHang2ActionPerformed
        // TODO add your handling code here:
        if ((int)txtSoLuong2.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập số lượng xuất kho!");
            txtSoLuong1.setFocusable(true);
        }
        

        int row = tblThongTinXuat.getSelectedRow();
        if (row != -1){
            int hoi = JOptionPane.showConfirmDialog(null, String.format(
                    "Bạn có muốn xuất nguyên liệu %s với số lượng %s được lưu trong phiếu xuất %s không", cboTenNguyenLieu.getSelectedItem().toString(), txtSoLuong2.getValue().toString(), tblThongTinXuat.getValueAt(row, 0)),
                    "Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.YES_NO_OPTION);
            if(hoi == JOptionPane.YES_OPTION){
                String manl = "";
                for(NguyenLieu nl : lstNguyenLieu){
                    if(nl.getTenNL().equals(cboTenNguyenLieu.getSelectedItem().toString()))
                        manl = nl.getMaNL();
                }
                ChiTietPhieuXuat ct = new ChiTietPhieuXuat(tblThongTinXuat.getValueAt(row, 0).toString(), manl, cboTenNguyenLieu.getSelectedItem().toString(), Integer.parseInt(txtSoLuong2.getValue().toString()));
                boolean temp = ChiTietPhieuXuatDAO.themMoiCTPX(ct);
                if(temp == true){
                    JOptionPane.showMessageDialog(null, "Thêm thành công chi tiết phiếu xuất");
                    loadTableInfo_XuatKho();
                    loadCTPX(tblThongTinXuat.getValueAt(row, 0).toString());
                    loadTableInfo_NguyenLieu();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Thêm thất bại chi tiết phiếu xuất");
            }
        }
        else{
            int x = JOptionPane.showConfirmDialog(null, "Bạn chưa chọn phiếu xuất muốn để lưu trữ, bạn có muốn thêm mới phiếu xuất không", "Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(x == JOptionPane.YES_OPTION){
                PhieuXuat px = new PhieuXuat( Run.tk.getMaNV(), txtGhiChu2.getText());
                boolean temp = PhieuXuatDAO.themMoiPhieuXuat(px);
                
                if(temp == true){
                    JOptionPane.showMessageDialog(null, "Thêm mới phiếu xuất thành công");
                    loadTableInfo_XuatKho();
                }
            }
        }
    }//GEN-LAST:event_btnThemMatHang2ActionPerformed

    private void tblNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguyenLieuMouseClicked
        // TODO add your handling code here:
        int row = tblNguyenLieu.getSelectedRow();

        txtTenNL.setText(tblNguyenLieu.getValueAt(row, 1).toString());
        txtDVT.setText(tblNguyenLieu.getValueAt(row, 2).toString());
        txtSoLuong.setText(tblNguyenLieu.getValueAt(row, 3).toString());

        txtMaNL.setText(tblNguyenLieu.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblNguyenLieuMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel)tblNguyenLieu.getModel();

        dtm.setRowCount(0);

        try {
            NguyenLieu nguyenlieu = NguyenLieuDAO.timKiemNguyenLieu(txtTimKiem.getText());

            if (nguyenlieu != null){
                Vector<Object> dia = new Vector<Object>();

                dia.add(nguyenlieu.getMaNL());
                dia.add(nguyenlieu.getTenNL());
                dia.add(nguyenlieu.getDVT());
                dia.add(nguyenlieu.getSoLuong());
                dtm.addRow(dia);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(NguyenLieuDAO.ktraNguyenLieuCoTonTai(txtMaNL.getText())== false){
            try {
                NguyenLieu nguyenlieu = new NguyenLieu();

                nguyenlieu.setMaNL(txtMaNL.getText());
                nguyenlieu.setTenNL(txtTenNL.getText());
                nguyenlieu.setDVT(txtDVT.getText());
                nguyenlieu.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

                boolean result = false;
                if(NguyenLieuDAO.ktraTonTai_NguyenLieu(txtMaNL.getText())){
                    JOptionPane.showConfirmDialog(null, "Tên bàn không được trùng", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);

                }else{
                    result = NguyenLieuDAO.themNguyenLieu(nguyenlieu);
                }

                if(result == false){
                    JOptionPane.showConfirmDialog(null, "Thêm thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
                else{
                    loadTableInfo_NguyenLieu();
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Mã Nguyên Liệu nhập bị trùng, bạn có muốn chỉnh sửa thông tin  không?", "Thông báo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                try {

                    NguyenLieu nguyenlieu = new NguyenLieu();

                    nguyenlieu.setMaNL(txtMaNL.getText());
                    nguyenlieu.setTenNL(txtTenNL.getText());
                    nguyenlieu.setDVT(txtDVT.getText());
                    nguyenlieu.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

                    boolean result = NguyenLieuDAO.capNhatThongTin_NguyenLieu(nguyenlieu);

                    if(result == false)
                    JOptionPane.showConfirmDialog(null, "Cập nhật thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    else{
                        loadTableInfo_NguyenLieu();
                        JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:

        boolean ktraTrung_MaNL = NguyenLieuDAO.ktraNguyenLieuCoTonTai(txtMaNL.getText());

        NguyenLieu nguyenlieu = new NguyenLieu();
        if(ktraTrung_MaNL == true){
            nguyenlieu.setMaNL(txtMaNL.getText());
            nguyenlieu.setTenNL(txtTenNL.getText());
            nguyenlieu.setDVT(txtDVT.getText());
            nguyenlieu.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

            boolean kq = NguyenLieuDAO.capNhatThongTin_NguyenLieu(nguyenlieu);
            if(kq){
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin Nguyên Liệu có mã %s thành công!!!!",txtMaNL.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfo_NguyenLieu();
            }
            else{
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin Nguyên Liệu có mã %s không thành công!!!!",txtMaNL.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            }
        }
        else{
            int temp = JOptionPane.showConfirmDialog(null, "Mã Nguyên Liệu không tồn tại trong danh sách, bạn có muốn thêm mới Nguyên Liệu không?","Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_OPTION);
            if(temp == JOptionPane.YES_OPTION){
                nguyenlieu.setMaNL(txtMaNL.getText());
                nguyenlieu.setTenNL(txtTenNL.getText());
                nguyenlieu.setDVT(txtDVT.getText());
                nguyenlieu.setSoLuong(Integer.parseInt(txtSoLuong.getText()));

                boolean kq = NguyenLieuDAO.themNguyenLieu(nguyenlieu);
                if(kq){
                    JOptionPane.showConfirmDialog(null, "Thêm Nguyên Liệu thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    loadTableInfo_NguyenLieu();
                }
                else{
                    JOptionPane.showConfirmDialog(null, "Thêm Nguyên Liệu không thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        loadTableInfo_NguyenLieu();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_NhapXuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_NhapXuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_NhapXuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_NhapXuatKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_NhapXuatKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnThemMatHang;
    private javax.swing.JButton btnThemMatHang2;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JComboBox<String> cboMaNguyenLieu;
    private javax.swing.JComboBox<String> cboMaNhaCC;
    private javax.swing.JComboBox<String> cboTenNguyenLieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNhap;
    private javax.swing.JPanel pnNhapDuLieu;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JPanel pnXuat;
    private javax.swing.JPanel pnXuatDuLieu;
    private javax.swing.JTable tblNguyenLieu;
    private javax.swing.JTable tblThongTinNhap;
    private javax.swing.JTable tblThongTinNhap1;
    private javax.swing.JTable tblThongTinXuat;
    private javax.swing.JTable tblThongTinXuat1;
    private javax.swing.JTextField txtDVT;
    private java.awt.TextArea txtGhiChu1;
    private java.awt.TextArea txtGhiChu2;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaNL;
    private javax.swing.JTextField txtMaNV1;
    private javax.swing.JTextField txtMaNV2;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtNgayXuat;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JSpinner txtSoLuong1;
    private javax.swing.JSpinner txtSoLuong2;
    private javax.swing.JTextField txtTenNL;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadDisplay() {
        this.setSize(1020, 680);
        this.setTitle("Nhập xuất kho");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        pnNhapDuLieu.setPreferredSize(new Dimension(907,234));
    
    }
    
    private void loadCombobox() {
        lstNguyenLieu = NguyenLieuDAO.layDSNguyenLieu();
        lstNhaCC = NhaCungCapDAO.layDSNhaCC();
        
        for (NguyenLieu nl : lstNguyenLieu){
            cboMaNguyenLieu.addItem(nl.getMaNL());
        }
        
        for (NhaCungCap ncc : lstNhaCC){
            cboMaNhaCC.addItem(ncc.getMaNCC());
        }
        
        for (NguyenLieu nl : lstNguyenLieu){
            cboTenNguyenLieu.addItem(nl.getTenNL());
        }
    }

    private void loadTableInfo_NhapKho() {
        lstPhieuNhap = PhieuNhapDAO.layDSPhieuNhap();
        dtm1.setRowCount(0);
        
        for(PhieuNhap pn : lstPhieuNhap){
            Vector<Object> dong = new Vector<Object>();
            dong.add(pn.getMaPN());
            dong.add(pn.getMaNCC());
            dong.add(pn.getNgayNhap());
            dong.add(pn.getGhiChu());
            dong.add(pn.getTienNhap());
            dong.add(pn.getMaNV());
            
            dtm1.addRow(dong);
        }
    }

    private void loadTableInfo_XuatKho() {
        lstPhieuXuat = PhieuXuatDAO.layDSPhieuXuat();
        dtm3.setRowCount(0);
        
        for(PhieuXuat px : lstPhieuXuat){
            Vector<Object> dong = new Vector<Object>();
            dong.add(px.getMaPX());
            dong.add(px.getMaNV());
            dong.add(px.getNgayXuat());
            dong.add(px.getGhiChu());
            
            dtm3.addRow(dong);
        }
    }

    private void loadCTPN(String mapn) {
        ArrayList<ChiTietPhieuNhap> lstChiTietPN = new ArrayList<>();
        lstChiTietPN = ChiTietPhieuNhapDAO.layDSChiTietPN(mapn);
        dtm2.setRowCount(0);
        for (ChiTietPhieuNhap ct : lstChiTietPN){
            Vector<Object> dong = new Vector<>();
            dong.add(ct.getMaPN());
            dong.add(ct.getMaNL());
            dong.add(ct.getTenNL());
            dong.add(ct.getSoLuong());
            dong.add(ct.getGiaNhap());
            dong.add(ct.getThanhTien());
            
            dtm2.addRow(dong);
        }
    }
    
    private void loadCTPX(String mapx) {
        ArrayList<ChiTietPhieuXuat> lstChiTietPX = new ArrayList<>();
        lstChiTietPX = ChiTietPhieuXuatDAO.layDSChiTietPX(mapx);
        dtm4.setRowCount(0);
        
        for (ChiTietPhieuXuat ct : lstChiTietPX){
            Vector<Object> dong = new Vector<>();
            dong.add(ct.getMaPX());
            dong.add(ct.getMaNL());
            dong.add(ct.getTenNL());
            dong.add(ct.getSoLuong());
            
            dtm4.addRow(dong);
        }
    }
    
    private void loadTableInfo_NguyenLieu() {
        lstNL = NguyenLieuDAO.layDSNguyenLieu();
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel)tblNguyenLieu.getModel();
        
        dtm.setNumRows(0);
        for(NguyenLieu nl : lstNL){
            Vector<Object> nguyenlieu = new Vector<>();
           
            
            nguyenlieu.add(nl.getMaNL());
            nguyenlieu.add(nl.getTenNL());
            nguyenlieu.add(nl.getDVT());
            nguyenlieu.add(nl.getSoLuong());
            
            dtm.addRow(nguyenlieu);
        }
    }
}
