/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.NhanVien;
import java.sql.ResultSet;
import pojo.TaiKhoan;

/**
 *
 * @author PC
 */
public class QL_NhanVien extends javax.swing.JFrame {

    Statement statement = null;
    PreparedStatement preStatement = null;
    Connection connection = null;
    ResultSet resultset = null;
    
    
    ArrayList<NhanVien> lstNV = new ArrayList<NhanVien>();
    /**
     * Creates new form QL_NhanVien
     */
    public QL_NhanVien() {
        initComponents();
        display();
        loadTableInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDsNhanVien = new javax.swing.JTable();
        pnLeft = new javax.swing.JPanel();
        lbTaiKhoan = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbMatKhau = new javax.swing.JLabel();
        lbNhapLaiMK = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtMatKhau1 = new javax.swing.JTextField();
        txtMatKhau2 = new javax.swing.JTextField();
        pnRight = new javax.swing.JPanel();
        lbMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lbGioiTinh = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lbSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lbChucVu = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        pnTimKiem = new javax.swing.JPanel();
        lbTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        lbIconSearch = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        pnButton = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(50, 67, 95));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tài khoản", "Họ và tên", "Ngày sinh", "Giới tính", "SĐT", "Địa chỉ", "Chức vụ"
            }
        ));
        tblDsNhanVien.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDsNhanVienAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblDsNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDsNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDsNhanVien);

        pnLeft.setBackground(new java.awt.Color(50, 67, 95));
        pnLeft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lbTaiKhoan.setText("Tài khoản");

        txtTenDN.setBackground(new java.awt.Color(50, 67, 95));
        txtTenDN.setForeground(new java.awt.Color(255, 255, 255));
        txtTenDN.setText("Nhập tên đăng nhập");
        txtTenDN.setBorder(null);

        lbMatKhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lbMatKhau.setText("Mật khẩu");

        lbNhapLaiMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNhapLaiMK.setForeground(new java.awt.Color(255, 255, 255));
        lbNhapLaiMK.setText("Nhập lại mật khẩu");

        lbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        lbDiaChi.setText("Địa chỉ");

        txtDiaChi.setBackground(new java.awt.Color(50, 67, 95));
        txtDiaChi.setForeground(new java.awt.Color(255, 255, 255));
        txtDiaChi.setText("Nhập địa chỉ");
        txtDiaChi.setBorder(null);

        txtMatKhau1.setBackground(new java.awt.Color(50, 67, 95));
        txtMatKhau1.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau1.setText("Nhập lại mật khẩu");
        txtMatKhau1.setBorder(null);
        txtMatKhau1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatKhau1FocusLost(evt);
            }
        });

        txtMatKhau2.setBackground(new java.awt.Color(50, 67, 95));
        txtMatKhau2.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau2.setText("Nhập mật khẩu");
        txtMatKhau2.setBorder(null);

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(txtTenDN, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(txtDiaChi)
                            .addComponent(jSeparator5)
                            .addComponent(txtMatKhau2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbMatKhau)
                    .addComponent(txtMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNhapLaiMK)
                    .addComponent(txtMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pnRight.setBackground(new java.awt.Color(50, 67, 95));
        pnRight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbMaNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMaNV.setForeground(new java.awt.Color(255, 255, 255));
        lbMaNV.setText("Mã nhân viên");

        txtMaNV.setBackground(new java.awt.Color(50, 67, 95));
        txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
        txtMaNV.setBorder(null);
        txtMaNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaNVFocusGained(evt);
            }
        });

        lbHoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));
        lbHoTen.setText("Họ và tên");

        txtHoTen.setBackground(new java.awt.Color(50, 67, 95));
        txtHoTen.setForeground(new java.awt.Color(255, 255, 255));
        txtHoTen.setText("Nhập họ tên");
        txtHoTen.setBorder(null);

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNgaySinh.setForeground(new java.awt.Color(255, 255, 255));
        lbNgaySinh.setText("Ngày sinh");

        txtNgaySinh.setBackground(new java.awt.Color(50, 67, 95));
        txtNgaySinh.setForeground(new java.awt.Color(255, 255, 255));
        txtNgaySinh.setText("Nhập ngày sinh");
        txtNgaySinh.setBorder(null);

        lbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        lbGioiTinh.setText("Giới tính");

        txtGioiTinh.setBackground(new java.awt.Color(50, 67, 95));
        txtGioiTinh.setForeground(new java.awt.Color(255, 255, 255));
        txtGioiTinh.setText("Nhập giới tính");
        txtGioiTinh.setBorder(null);

        lbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSDT.setForeground(new java.awt.Color(255, 255, 255));
        lbSDT.setText("SĐT");

        txtSDT.setBackground(new java.awt.Color(50, 67, 95));
        txtSDT.setForeground(new java.awt.Color(255, 255, 255));
        txtSDT.setText("Nhập số điện thoại");
        txtSDT.setBorder(null);

        lbChucVu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lbChucVu.setText("Chức vụ");

        txtChucVu.setBackground(new java.awt.Color(50, 67, 95));
        txtChucVu.setForeground(new java.awt.Color(255, 255, 255));
        txtChucVu.setText("Nhập chức vụ");
        txtChucVu.setBorder(null);

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2)
                                        .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator6)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator7)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator8)
                                .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator10)
                        .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNgaySinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGioiTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbChucVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnTimKiem.setBackground(new java.awt.Color(50, 67, 95));

        lbTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        lbTimKiem.setText("Tìm kiếm nhân viên theo mã nhân viên");

        txtTimKiem.setBackground(new java.awt.Color(50, 67, 95));
        txtTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        txtTimKiem.setText("Nhập mã nhân viên");
        txtTimKiem.setBorder(null);
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
        });

        lbIconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbIconSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator11)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnTim))
                    .addComponent(lbTimKiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconSearch)
                    .addComponent(lbTimKiem))
                .addGap(18, 18, 18)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTimKiemLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnButton.setBackground(new java.awt.Color(50, 67, 95));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(65, 23));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(65, 23));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new java.awt.Dimension(65, 23));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnButtonLayout = new javax.swing.GroupLayout(pnButton);
        pnButton.setLayout(pnButtonLayout);
        pnButtonLayout.setHorizontalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnButtonLayout.setVerticalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMainLayout.createSequentialGroup()
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        txtTimKiem.setText("");
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtMaNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNVFocusGained
        // TODO add your handling code here:
        txtMaNV.setText("");
    }//GEN-LAST:event_txtMaNVFocusGained

    //Thêm NV
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
       if(NhanVienDAO.ktraNVCoTonTai(txtMaNV.getText())== false){
            try {
                NhanVien nv = new NhanVien(txtHoTen.getText(), txtNgaySinh.getText(), txtSDT.getText(), txtChucVu.getText(), txtDiaChi.getText(), txtGioiTinh.getText());
                TaiKhoan tk = new TaiKhoan(txtTenDN.getText(), txtMatKhau1.getText());
                boolean result = false;
                if(NhanVienDAO.ktraNV_TrungTenDN(txtTenDN.getText())){
                    JOptionPane.showConfirmDialog(null, "Tên đăng nhập không được trùng", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                
                }else{
                    result = NhanVienDAO.themNhanVien(nv,tk);
                }
                
                if(result == false){
                    JOptionPane.showConfirmDialog(null, "Thêm thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
                else{
                    loadTableInfo();
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Mã nv nhập bị trùng, bạn có muốn chỉnh sửa thông tin nv không?", "Thông báo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                try {
                    NhanVien nv = new NhanVien(txtMaNV.getText(),txtHoTen.getText(), txtNgaySinh.getText(), txtSDT.getText(), txtChucVu.getText(), txtDiaChi.getText(), txtGioiTinh.getText());
                    boolean result = NhanVienDAO.capNhatThongTin_NhanVien(nv);
                    
                    if(result == false)
                        JOptionPane.showConfirmDialog(null, "Cập nhật thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    else{
                        loadTableInfo();
                        JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    //Xóa NV
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        boolean result = NhanVienDAO.xoa1NhanVien(txtMaNV.getText());
        try {
           
            if(result == false)
                JOptionPane.showConfirmDialog(null, "Xóa thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            else{
                JOptionPane.showConfirmDialog(null, "Xóa thành công!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfo();
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    //Tìm NV
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel)tblDsNhanVien.getModel();
        
        dtm.setRowCount(0);
        // TODO add your handling code here:
        try {
            NhanVien nv = NhanVienDAO.layNhanVien(txtTimKiem.getText());
            TaiKhoan tk = TaiKhoanDAO.layTaiKhoan_TheoMaNV(txtTimKiem.getText());
            if (nv != null){
                Vector<Object> dia = new Vector<Object>();

                dia.add(nv.getMaNV());
                dia.add(tk.getTenDN());
                dia.add(nv.getTenNV());
                dia.add(nv.getNgaySinh());
                dia.add(nv.getSDT());
                dia.add(nv.getChucVu());
                dia.add(nv.getDiaChi());
                dia.add(nv.getGioiTinh());


                dtm.addRow(dia);

            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblDsNhanVienAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDsNhanVienAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblDsNhanVienAncestorAdded

    private void tblDsNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tblDsNhanVien.getSelectedRow();
        
        txtHoTen.setText(tblDsNhanVien.getValueAt(row, 2).toString());
        txtNgaySinh.setText(tblDsNhanVien.getValueAt(row, 3).toString());
        txtGioiTinh.setText(tblDsNhanVien.getValueAt(row, 4).toString());
        txtSDT.setText(tblDsNhanVien.getValueAt(row, 5).toString());
        txtDiaChi.setText(tblDsNhanVien.getValueAt(row, 6).toString());
        txtChucVu.setText(tblDsNhanVien.getValueAt(row, 7).toString());
        txtTenDN.setText(tblDsNhanVien.getValueAt(row, 1).toString());
        txtMaNV.setText(tblDsNhanVien.getValueAt(row, 0).toString());
        
        
    }//GEN-LAST:event_tblDsNhanVienMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        boolean ktraTrung_MaNV = NhanVienDAO.ktraNVCoTonTai(txtMaNV.getText());
        
        NhanVien nv = new NhanVien();
        TaiKhoan tk;
        if(ktraTrung_MaNV == true){
            nv.setMaNV(txtMaNV.getText());
            nv.setTenNV(txtHoTen.getText());
            nv.setChucVu(txtChucVu.getText());
            nv.setDiaChi(txtDiaChi.getText());
            nv.setGioiTinh(txtGioiTinh.getText());
            nv.setNgaySinh(txtNgaySinh.getText());
            nv.setSDT(txtSDT.getText());
            
            boolean kq = NhanVienDAO.capNhatThongTin_NhanVien(nv);
            if(kq){
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin nhân viên có mã %s thành công!!!!",txtMaNV.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfo();
            }
            else{
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin nhân viên có mã %s không thành công!!!!",txtMaNV.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            }
        }
        else{
            int temp = JOptionPane.showConfirmDialog(null, "Mã nhân viên không tồn tại trong danh sách, bạn có muốn thêm mới nhân viên không?","Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_OPTION);
            tk = new TaiKhoan(txtTenDN.getText(), txtMatKhau1.getText());
            if(temp == JOptionPane.YES_OPTION){
                nv.setMaNV(txtMaNV.getText());
                nv.setTenNV(txtHoTen.getText());
                nv.setChucVu(txtChucVu.getText());
                nv.setDiaChi(txtDiaChi.getText());
                nv.setGioiTinh(txtGioiTinh.getText());
                nv.setNgaySinh(txtNgaySinh.getText());
                nv.setSDT(txtSDT.getText());
                boolean kq = NhanVienDAO.themNhanVien(nv, tk);
                if(kq){
                    JOptionPane.showConfirmDialog(null, "Thêm nhân viên thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    loadTableInfo();
                }
                else{
                    JOptionPane.showConfirmDialog(null, "Thêm nhân viên không thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMatKhau1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatKhau1FocusLost
        // TODO add your handling code here:
        if(txtMatKhau1.getText().equals(txtMatKhau2.getText()) == false){
            JOptionPane.showMessageDialog(null, "Bạn nhập sai mật khẩu, mời nhập lại");
            txtMatKhau2.setText("");
            txtMatKhau2.requestFocus();
        }
    }//GEN-LAST:event_txtMatKhau1FocusLost

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        loadTableInfo();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbIconSearch;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbNhapLaiMK;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JTable tblDsNhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau1;
    private javax.swing.JTextField txtMatKhau2;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void display() {
        this.setSize(770, 640);
        this.setTitle("Quản lý nhân viên");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    //DanhSachNV
    private void loadTableInfo() {
        lstNV = NhanVienDAO.layDSNhanVien();
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm = (DefaultTableModel)tblDsNhanVien.getModel();
        
        dtm.setNumRows(0);
        for(NhanVien nv : lstNV){
            Vector<Object> nhanvien = new Vector<>();
            TaiKhoan tk = new TaiKhoan();
            tk = TaiKhoanDAO.layTaiKhoan_TheoMaNV(nv.getMaNV());
            
            nhanvien.add(nv.getMaNV());
            nhanvien.add(tk.getTenDN());
            nhanvien.add(nv.getTenNV());
            nhanvien.add(nv.getNgaySinh());
            nhanvien.add(nv.getGioiTinh());
            
            nhanvien.add(nv.getSDT());
            nhanvien.add(nv.getDiaChi());
            nhanvien.add(nv.getChucVu());
            
            dtm.addRow(nhanvien);
        }
    }
    
}
