/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dao.LoaiHangDAO;
import dao.NhanVienDAO;
import dao.SanPhamDAO;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.LoaiHang;
import pojo.SanPham;

/**
 *
 * @author PC
 */
public class QL_SanPham extends javax.swing.JFrame {
Statement statement = null;
    PreparedStatement preStatement = null;
    Connection connection = null;
     ResultSet resultset = null;
    //DefaultTableModel dtm = new DefaultTableModel();
     
       ArrayList<SanPham> lstSP = new ArrayList<SanPham>();
       ArrayList<LoaiHang> lstLHang = new ArrayList<LoaiHang>();
       DefaultTableModel dtm = new DefaultTableModel();
       DefaultTableModel dtm2 = new DefaultTableModel();
        
        
    /**
     * Creates new form QL_SanPham
     */
    public QL_SanPham() {
        initComponents();
        display();
        dtm = (DefaultTableModel)tblDsLoaiSP.getModel();
        dtm2 = (DefaultTableModel)tblDsHang.getModel();
        loadTableInfoSP();
        loadTableInfoLHang();
        loadComboboxTimKiem();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnLoaiSanPham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDsLoaiSP = new javax.swing.JTable();
        pnThongTin1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaLoaiHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenLoaiHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMoTa = new javax.swing.JTextArea();
        pnButton1 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        pnTimKiem1 = new javax.swing.JPanel();
        btnTimKiem1 = new javax.swing.JButton();
        cboTimKiem = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        pnSanPham = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDsHang = new javax.swing.JTable();
        pnThongTinHang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLoaiHang = new javax.swing.JTextField();
        pnButton2 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        pnTimKiem2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cboTimKiem2 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnTimKiem = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 138, 77));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnLoaiSanPham.setBackground(new java.awt.Color(204, 138, 77));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDsLoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại", "Tên loại", "Mô tả"
            }
        ));
        tblDsLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDsLoaiSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDsLoaiSP);

        pnThongTin1.setBackground(new java.awt.Color(204, 138, 77));

        jLabel1.setText("Mã loại");

        jLabel2.setText("Tên loại");

        jLabel3.setText("Mô tả");

        txtAMoTa.setColumns(10);
        txtAMoTa.setRows(5);
        jScrollPane2.setViewportView(txtAMoTa);

        javax.swing.GroupLayout pnThongTin1Layout = new javax.swing.GroupLayout(pnThongTin1);
        pnThongTin1.setLayout(pnThongTin1Layout);
        pnThongTin1Layout.setHorizontalGroup(
            pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnThongTin1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(pnThongTin1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addGap(10, 10, 10)))
                    .addGroup(pnThongTin1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(txtMaLoaiHang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenLoaiHang, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26))
        );
        pnThongTin1Layout.setVerticalGroup(
            pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTin1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnThongTin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnButton1.setBackground(new java.awt.Color(204, 138, 77));

        btnThem1.setBackground(new java.awt.Color(189, 189, 191));
        btnThem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(189, 189, 191));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(189, 189, 191));
        btnSua1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnButton1Layout = new javax.swing.GroupLayout(pnButton1);
        pnButton1.setLayout(pnButton1Layout);
        pnButton1Layout.setHorizontalGroup(
            pnButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pnButton1Layout.setVerticalGroup(
            pnButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButton1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnXoa1)
                    .addComponent(btnSua1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTimKiem1.setBackground(new java.awt.Color(204, 138, 77));

        btnTimKiem1.setBackground(new java.awt.Color(189, 189, 191));
        btnTimKiem1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimKiem1.setText("Tìm");
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tìm kiếm");

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiem1Layout = new javax.swing.GroupLayout(pnTimKiem1);
        pnTimKiem1.setLayout(pnTimKiem1Layout);
        pnTimKiem1Layout.setHorizontalGroup(
            pnTimKiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnTimKiem1Layout.createSequentialGroup()
                        .addComponent(btnTimKiem1)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(cboTimKiem, 0, 158, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnTimKiem1Layout.setVerticalGroup(
            pnTimKiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(cboTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnTimKiem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem1)
                    .addComponent(btnReset1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnLoaiSanPhamLayout = new javax.swing.GroupLayout(pnLoaiSanPham);
        pnLoaiSanPham.setLayout(pnLoaiSanPhamLayout);
        pnLoaiSanPhamLayout.setHorizontalGroup(
            pnLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoaiSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(pnLoaiSanPhamLayout.createSequentialGroup()
                        .addGroup(pnLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnThongTin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnLoaiSanPhamLayout.setVerticalGroup(
            pnLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoaiSanPhamLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLoaiSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThongTin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại hàng", pnLoaiSanPham);

        pnSanPham.setBackground(new java.awt.Color(85, 128, 160));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblDsHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Mã loại hàng", "Đơn giá"
            }
        ));
        tblDsHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDsHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDsHang);

        pnThongTinHang.setBackground(new java.awt.Color(85, 128, 160));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Mã hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tên hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Đơn giá");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Loại hàng");

        javax.swing.GroupLayout pnThongTinHangLayout = new javax.swing.GroupLayout(pnThongTinHang);
        pnThongTinHang.setLayout(pnThongTinHangLayout);
        pnThongTinHangLayout.setHorizontalGroup(
            pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinHangLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnThongTinHangLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThongTinHangLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThongTinHangLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnThongTinHangLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLoaiHang)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnThongTinHangLayout.setVerticalGroup(
            pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinHangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnButton2.setBackground(new java.awt.Color(85, 128, 160));

        btnThem2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXoa2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnSua2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnButton2Layout = new javax.swing.GroupLayout(pnButton2);
        pnButton2.setLayout(pnButton2Layout);
        pnButton2Layout.setHorizontalGroup(
            pnButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButton2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua2)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnButton2Layout.setVerticalGroup(
            pnButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem2)
                    .addComponent(btnXoa2)
                    .addComponent(btnSua2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnTimKiem2.setBackground(new java.awt.Color(85, 128, 160));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tìm kiếm");

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiem2Layout = new javax.swing.GroupLayout(pnTimKiem2);
        pnTimKiem2.setLayout(pnTimKiem2Layout);
        pnTimKiem2Layout.setHorizontalGroup(
            pnTimKiem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiem2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(cboTimKiem2, 0, 178, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiem2Layout.createSequentialGroup()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnTimKiem2Layout.setVerticalGroup(
            pnTimKiem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cboTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTimKiem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnReset2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnSanPhamLayout.createSequentialGroup()
                        .addComponent(pnThongTinHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(pnTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSanPhamLayout.createSequentialGroup()
                        .addComponent(pnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnThongTinHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản phẩm", pnSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Them Hàng
    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
        if(SanPhamDAO.ktraSPCoTonTai(txtMaHang.getText())== false){
            try {
                SanPham sp = new SanPham(txtMaHang.getText(), txtTenHang.getText(), txtLoaiHang.getText(), BigDecimal.valueOf(Double.parseDouble(txtDonGia.getText())));
               
                boolean result = false;
                if(SanPhamDAO.ktraSanPham_TrungTen(txtTenHang.getText())){
                    JOptionPane.showConfirmDialog(null, "Tên  Hàng không được trùng", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                
                }else{
                    result = SanPhamDAO.themSanPham(sp);
                }
                
                if(result == false){
                    JOptionPane.showConfirmDialog(null, "Thêm thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
                else{
                    
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                    loadTableInfoSP();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Mã Hàng nhập bị trùng, bạn có muốn chỉnh sửa thông tin hàng không?", "Thông báo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                try {
                    
                    SanPham sp = new SanPham(txtMaHang.getText(),txtTenHang.getText(), txtLoaiHang.getText(), BigDecimal.valueOf(Double.parseDouble(txtDonGia.getText())));
                    boolean result = SanPhamDAO.capNhatThongTin_Hang(sp);
                    
                    if(result == false)
                        JOptionPane.showConfirmDialog(null, "Cập nhật thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    else{
                        loadTableInfoSP();
                        JOptionPane.showConfirmDialog(null, "Cập nhật thành công!","Thông báo",JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_btnThem2ActionPerformed
//xóa Sản Phẩm(Hàng)
    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        boolean result = SanPhamDAO.xoa1SanPham(txtMaHang.getText());
        try {
           
            if(result == false)
                JOptionPane.showConfirmDialog(null, "Xóa thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            else{
                JOptionPane.showConfirmDialog(null, "Xóa thành công!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfoSP();
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btnXoa2ActionPerformed
//Tìm kiêm Sản Phẩm (Hàng)
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        SanPham sp = new SanPham();
        sp = SanPhamDAO.lay1SanPham_theoTenHang(cboTimKiem2.getSelectedItem().toString());
        
        dtm2.setRowCount(0);
        
        Vector<Object> dong = new Vector<>();
        dong.add(sp.getMaHang());
        dong.add(sp.getTenHang());
        dong.add(sp.getMaLoaiHang());
        dong.add(sp.getDonGia());
        
        dtm2.addRow(dong);
          
       
    }//GEN-LAST:event_btnTimKiemActionPerformed

    
    //Them Loại Hàng
    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
         if(LoaiHangDAO.ktraLHCoTonTai(txtMaLoaiHang.getText())== false){
            try {
                LoaiHang lh = new LoaiHang(txtMaLoaiHang.getText(),txtTenLoaiHang.getText(), txtAMoTa.getText());
               
                boolean result = false;
                if(LoaiHangDAO.ktraLoaiHang_TrungTen(txtTenHang.getText())){
                    JOptionPane.showConfirmDialog(null, "Tên Loại Hàng không được trùng", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                
                }else{
                    result = LoaiHangDAO.themLoaiHang(lh);
                }
                
                if(result == false){
                    JOptionPane.showConfirmDialog(null, "Thêm thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
                else{
                    loadTableInfoLHang();
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Mã Loại Hàng nhập bị trùng, bạn có muốn chỉnh sửa thông tin không?", "Thông báo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                try {
                    LoaiHang lh = new LoaiHang(txtMaLoaiHang.getText(),txtTenLoaiHang.getText(), txtAMoTa.getText());
                    boolean result = LoaiHangDAO.capNhatThongTin_LoaiHang(lh);
                    
                    if(result == false)
                        JOptionPane.showConfirmDialog(null, "Cập nhật thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    else{
                        loadTableInfoLHang();
                        JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.OK_OPTION);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }


    }//GEN-LAST:event_btnThem1ActionPerformed
//Xoa Loại Hang
    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        boolean result = LoaiHangDAO.xoa1LoaiHang(txtMaLoaiHang.getText());
        try {
           
            if(result == false)
                JOptionPane.showConfirmDialog(null, "Xóa thất bại!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            else{
                JOptionPane.showConfirmDialog(null, "Xóa thành công!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfoSP();
            }
                
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnXoa1ActionPerformed
    //click chuột LoaiHang
    private void tblDsLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsLoaiSPMouseClicked
        // TODO add your handling code here:
        int row = tblDsLoaiSP.getSelectedRow();
        
        txtMaLoaiHang.setText(tblDsLoaiSP.getValueAt(row, 0).toString());
        txtTenLoaiHang.setText(tblDsLoaiSP.getValueAt(row, 1).toString());
        String s = "";
        if(tblDsLoaiSP.getValueAt(row, 2).toString() != null)
            s = tblDsLoaiSP.getValueAt(row, 2).toString();
        txtAMoTa.setText(s);
        
    }//GEN-LAST:event_tblDsLoaiSPMouseClicked
        //click chuột SanPham
    private void tblDsHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsHangMouseClicked
        // TODO add your handling code here:
        int row = tblDsHang.getSelectedRow();
        
        txtMaHang.setText(tblDsHang.getValueAt(row, 0).toString());
        txtTenHang.setText(tblDsHang.getValueAt(row, 1).toString());
        txtLoaiHang.setText(tblDsHang.getValueAt(row, 2).toString());
        txtDonGia.setText(tblDsHang.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblDsHangMouseClicked
    //Sửa Thông tin Sản Phẩm(Hàng)
    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
        boolean ktraTrung_MaHang = SanPhamDAO.ktraSPCoTonTai(txtMaHang.getText());
        
        SanPham sp = new SanPham();
        if(ktraTrung_MaHang == true){
            sp.setMaHang(txtMaHang.getText());
            sp.setTenHang(txtTenHang.getText());
            sp.setMaLoaiHang(txtLoaiHang.getText());
            sp.setDonGia(BigDecimal.valueOf(Double.parseDouble(txtDonGia.getText())));
           
            
            
            boolean kq = SanPhamDAO.capNhatThongTin_Hang(sp);
            if(kq){
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin có mã %s thành công!!!!",txtMaHang.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfoSP();
            }
            else{
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin có mã %s không thành công!!!!",txtMaHang.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            }
        }
        else{
            int temp = JOptionPane.showConfirmDialog(null, "Mã Sản phẩm không tồn tại trong danh sách, bạn có muốn thêm mới không?","Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_OPTION);
            if(temp == JOptionPane.YES_OPTION){
                sp.setMaHang(txtMaHang.getText());
                sp.setTenHang(txtTenHang.getText());
                sp.setMaLoaiHang(txtLoaiHang.getText());
                sp.setDonGia(BigDecimal.valueOf(Double.parseDouble(txtDonGia.getText())));
           
                               
                boolean kq = SanPhamDAO.themSanPham(sp);
                if(kq){
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    loadTableInfoSP();
                }
                else{
                    JOptionPane.showConfirmDialog(null, "Thêm không thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btnSua2ActionPerformed
    //Sửa 1 loại Hàng
    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        boolean ktraTrung_MaLoaiHang = LoaiHangDAO.ktraLHCoTonTai(txtMaLoaiHang.getText());
        
        LoaiHang lh = new LoaiHang();
        if(ktraTrung_MaLoaiHang == true){
            lh.setMaLoai(txtMaLoaiHang.getText());
            lh.setTenLoaiHang(txtTenLoaiHang.getText());
            lh.setMoTa(txtAMoTa.getText());
            
           
            
            
            boolean kq = LoaiHangDAO.capNhatThongTin_LoaiHang(lh);
            if(kq){
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin có mã %s thành công!!!!",txtMaHang.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                loadTableInfoLHang();
            }
            else{
                JOptionPane.showConfirmDialog(null, String.format("Cập nhật thông tin có mã %s không thành công!!!!",txtMaHang.getText()),"Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
            }
        }
        else{
            int temp = JOptionPane.showConfirmDialog(null, "Mã không tồn tại trong danh sách, bạn có muốn thêm mới không?","Thông báo", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_OPTION);
            if(temp == JOptionPane.YES_OPTION){
                lh.setMaLoai(txtMaLoaiHang.getText());
                lh.setTenLoaiHang(txtTenLoaiHang.getText());
                lh.setMoTa(txtAMoTa.getText());
           
                               
                boolean kq = LoaiHangDAO.themLoaiHang(lh);
                if(kq){
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                    loadTableInfoLHang();
                }
                else{
                    JOptionPane.showConfirmDialog(null, "Thêm không thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE,JOptionPane.OK_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        loadTableInfoLHang();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
        // TODO add your handling code here:
        LoaiHang lh = new LoaiHang();
        lh = LoaiHangDAO.layLoaiHang(cboTimKiem.getSelectedItem().toString());
        
        dtm.setRowCount(0);
        Vector<Object> dong = new Vector<>();
        dong.add(lh.getMaLoai());
        dong.add(lh.getTenLoaiHang());
        dong.add(lh.getMoTa());
        
        dtm.addRow(dong);
    }//GEN-LAST:event_btnTimKiem1ActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        loadTableInfoSP();
    }//GEN-LAST:event_btnReset2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_SanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JComboBox<String> cboTimKiem;
    private javax.swing.JComboBox<String> cboTimKiem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnButton1;
    private javax.swing.JPanel pnButton2;
    private javax.swing.JPanel pnLoaiSanPham;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JPanel pnThongTin1;
    private javax.swing.JPanel pnThongTinHang;
    private javax.swing.JPanel pnTimKiem1;
    private javax.swing.JPanel pnTimKiem2;
    private javax.swing.JTable tblDsHang;
    private javax.swing.JTable tblDsLoaiSP;
    private javax.swing.JTextArea txtAMoTa;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtLoaiHang;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtMaLoaiHang;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtTenLoaiHang;
    // End of variables declaration//GEN-END:variables

    private void display() {
        this.setTitle("Quản lý sản phẩm");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    //DanhSachSP
    private void loadTableInfoSP() {
        lstSP = SanPhamDAO.layDSSanPham();
        
        
        dtm2.setNumRows(0);
        for(SanPham sp : lstSP){
            Vector<Object> sanpham = new Vector<>();
            
            sanpham.add(sp.getMaHang());
            sanpham.add(sp.getTenHang());
            sanpham.add(sp.getMaLoaiHang());
            sanpham.add(sp.getDonGia());
            dtm2.addRow(sanpham);
        }
    }
         //DanhSach Loai hang
    private void loadTableInfoLHang() {
        lstLHang = LoaiHangDAO.layDsLoaiHang();

        dtm.setNumRows(0);
        for(LoaiHang lh : lstLHang){
            Vector<Object> LoaiHang = new Vector<>();
            
            LoaiHang.add(lh.getMaLoai());
            LoaiHang.add(lh.getTenLoaiHang());
            LoaiHang.add(lh.getMoTa());
            dtm.addRow(LoaiHang);
        }
    }

    private void loadComboboxTimKiem() {
        for (LoaiHang lh : lstLHang){
            cboTimKiem.addItem(lh.getTenLoaiHang());
        }
        for (SanPham sp : lstSP){
            cboTimKiem2.addItem(sp.getTenHang());
        }
    }
    



}
